export const githubLinks = {
  organisation: 'https://github.com/Robertogag',
  mes: 'https://github.com/Chunil-Mexico/MES-System',
  erp: 'https://github.com/Chunil-Mexico/ERP-System',
};

export const contactLinks = {
  email: 'mailto:roberto.gag117@gmail.com',
  emailLabel: 'roberto.gag117@gmail.com',
  linkedin: 'https://www.linkedin.com/in/juan-roberto-garc%C3%ADa-g%C3%B3mez1/',
};

const C = '/assets/images/captures';

export const portfolioAssets = {
  cv: '/assets/docs/juan-roberto-garcia-cv-2026.pdf',
  profile: '/assets/images/roberto-profile-cv2.png',

  // MES captures (fresh, logged in — Aug 2026)
  mesHome: `${C}/mes-home.jpg`,
  mesRealtime: `${C}/mes-realtime-dashboard.png`,
  mesAssemblyRealtime: `${C}/mes-assembly-realtime.png`,
  mesSemiautoRealtime: `${C}/mes-semiauto-realtime.png`,
  mesEpcCoverage: `${C}/mes-epc-coverage.png`,
  mesShiftAnalytics: `${C}/mes-shift-analytics.png`,
  mesHistorical: `${C}/mes-historical.png`,
  mesLineStopHistory: '/assets/images/mes-line-stop-history.png',
  mesInjectionData: `${C}/mes-injection-data.png`,
  mesAssemblyData: `${C}/mes-assembly-data-live.png`,
  mesEpcData: `${C}/mes-epc-data.png`,
  mesPmRuntime: `${C}/mes-pm-runtime.png`,
  mesMoldTracking: `${C}/mes-mold-tracking.png`,
  mesMaintenanceOrders: `${C}/mes-maintenance-orders.png`,
  toolingPm: `${C}/mes-pm-runtime.png`,
  moldTracking: `${C}/mes-mold-tracking.png`,
  moldMaintenanceOrders: `${C}/mes-maintenance-orders.png`,
  mesRegrind: `${C}/mes-regrind.png`,
  mesQuarantine: `${C}/mes-quarantine.png`,
  mesDocumentControl: `${C}/mes-document-control.png`,

  // ERP captures
  erpHome: `${C}/erp-home.jpg`,
  erpProductionPlan: `${C}/erp-production-plan.png`,
  erpHrIncidencias: `${C}/erp-hr-incidencias.png`,
  erpWarehouse: `${C}/erp-warehouse.jpg`,
  erpFinances: `${C}/erp-finances.png`,
  erpSales: `${C}/erp-sales.png`,
  erpTrialBalance: `${C}/erp-trial-balance.jpg`,

  // Inventory Scanner App (mobile / Expo)
  scannerHome: `${C}/scanner-home.png`,
  scannerInventario: `${C}/scanner-inventario.png`,
  scannerResinas: `${C}/scanner-resinas.png`,
  scannerSubsidiarios: `${C}/scanner-subsidiarios.png`,
  scannerStock: `${C}/scanner-stock.png`,
  scannerLotes: `${C}/scanner-lotes.png`,
  scannerNotificaciones: `${C}/scanner-notificaciones.png`,
  scannerAdmin: `${C}/scanner-admin.png`,

  // Analytics
  weeklyReportSummary: '/assets/images/reports/weekly-report-summary.png',
  weeklyReportTrend: '/assets/images/reports/weekly-report-trend.png',
  powerbiPlan: '/assets/images/powerbi/powerbi-plan-adherence.png',
  powerbiDrivers: '/assets/images/powerbi/powerbi-performance-drivers.png',

  // Recognition
  gm: '/assets/images/highlights/gm.jpg',
  keepCoding: '/assets/images/highlights/keepcoding.jpg',
  award: '/assets/images/highlights/department-employee-of-the-year.jpg',
  bootcampBookshop: '/assets/images/bootcamp/bookshop-api-tests.png',
  bootcampReactDashboard: '/assets/images/bootcamp/react-product-dashboard.png',
  bootcampStreambox: '/assets/images/bootcamp/streambox-home-overview.png',
  bootcampSql: '/assets/images/bootcamp/videoclub-erd.png',
  bootcampJs: '/assets/images/bootcamp/javascript-foundations.jpg',
};

export const contentByLanguage = {
  en: {
    brandRole: 'Data Engineer · MES · Industrial IoT',
    imageZoomLabel: 'Open image',
    imageCloseLabel: 'Close image preview',
    navigation: [
      { label: 'Impact', href: '#impact' },
      { label: 'MES', href: '#mes' },
      { label: 'ERP', href: '#erp' },
      { label: 'Scanner', href: '#scanner' },
      { label: 'Analytics', href: '#analytics' },
      { label: 'Experience', href: '#experience' },
      { label: 'Contact', href: '#contact' },
    ],
    languageSwitchLabel: 'Select language',
    cvLabel: 'Download CV',
    githubLabel: 'GitHub',
    hero: {
      eyebrow: 'Data Engineer · Manufacturing Systems',
      titleLead: 'I build manufacturing systems that turn',
      titleAccent: 'live data into daily control.',
      description:
        "I'm Juan Roberto García Gómez. I design and ship the software a plant actually runs on — a real-time MES, an ERP, industrial IoT integration and the analytics leadership reviews every morning.",
      primaryAction: 'See the systems',
      secondaryAction: 'Download CV',
      linkedin: 'LinkedIn',
      portraitAlt: 'Professional portrait of Juan Roberto García Gómez',
      focusTitle: 'What I deliver end to end',
      focusItems: [
        'Real-time MES dashboards for the shopfloor and leadership',
        'Production, downtime, quality, tooling and planning modules in daily use',
        'Machine integration, ETL pipelines and Power BI on top of MES + ERP',
      ],
    },
    impact: {
      eyebrow: 'Impact',
      title: 'Outcomes, not just screens',
      description:
        'Every number below comes from systems running in production at a plastic-injection plant in San Luis Potosí.',
      stats: [
        {
          value: '34',
          label: 'machines connected',
          detail: 'EUROMAP63 and Modbus integration across ENGEL, WOOJIN and SUMITOMO injection machines — plus 14 semiautomatic stations and every manual assembly station live.',
        },
        {
          value: '90%',
          label: 'less manual reporting',
          detail: 'Production now arrives in real time; operators only add downtime and defect context.',
        },
        {
          value: '24/7',
          label: 'plan visibility',
          detail: 'Leadership sees plan vs. actual, stop causes and production running without a plan, live.',
        },
        {
          value: '6',
          label: 'plant areas unified',
          detail: 'Injection, assembly, EPC, tooling, quality and maintenance in one connected MES + ERP platform.',
        },
      ],
    },
    mes: {
      eyebrow: 'Flagship · MES-System',
      title: 'A real-time MES the plant runs on',
      description:
        'One web platform that centralizes injection, assembly, EPC, tooling, quality and live machine data — built with React and Node.js, backed by PostgreSQL.',
      featured: {
        title: 'Live Stop Board & Machine Status',
        subtitle: 'Real-time shopfloor control',
        browserLabel: 'mes.chunil.mx/realtime-data/dashboard',
        image: portfolioAssets.mesRealtime,
        alt: 'Real-time MES dashboard showing live machine status for the whole plant',
        text: 'A single operational screen showing the state of every machine, the live stop board and plan exceptions — so supervisors react the moment production changes during a shift.',
        metrics: [
          { value: '34', label: 'machines live' },
          { value: '3', label: 'shifts/day' },
          { value: 'Socket.IO', label: 'real-time feed' },
          { value: 'React + Node', label: 'full stack' },
        ],
      },
      galleryTitle: 'Inside the MES',
      galleryDescription: 'Core modules used across injection, tooling, quality and EPC every shift.',
      gallery: [
        {
          title: 'Modules Home',
          subtitle: 'Unified entry point',
          browserLabel: 'mes.chunil.mx/home',
          image: portfolioAssets.mesHome,
          alt: 'MES home with access to every module',
          description: 'Role-aware landing page with direct access to every module and live context.',
        },
        {
          title: 'Assembly Live — Manual Stations',
          subtitle: 'Every station, every shift, live',
          browserLabel: 'mes.chunil.mx/realtime-data/assembly/dashboard',
          image: portfolioAssets.mesAssemblyRealtime,
          alt: 'Live assembly dashboard with one card per manual station',
          description: 'One live card per manual station — part, operator, run/stop timers, boxes and progress against the shift plan.',
        },
        {
          title: 'Semiautomatic Stations',
          subtitle: 'Leak testers streaming from PLCs',
          browserLabel: 'mes.chunil.mx/realtime-data/assembly/semiauto',
          image: portfolioAssets.mesSemiautoRealtime,
          alt: 'Live dashboard of semiautomatic leak-test stations',
          description: 'Leak testers and semiautomatic machines streaming PLC counters live, with stop reasons and pending-justification alerts.',
        },
        {
          title: 'EPC Shipping Coverage',
          subtitle: 'Inventory vs. forecast, 8 weeks out',
          browserLabel: 'mes.chunil.mx/realtime-data/epc-coverage',
          image: portfolioAssets.mesEpcCoverage,
          alt: 'EPC shipping coverage table of inventory versus forecast by week',
          description: 'Live coverage of inventory against the customer forecast per part — flagging the exact week each part runs out.',
        },
        {
          title: 'Shift Analytics',
          subtitle: 'OEE audit by engineer and week',
          browserLabel: 'mes.chunil.mx/realtime-data/shift-analytics',
          image: portfolioAssets.mesShiftAnalytics,
          alt: 'Shift analytics dashboard with OEE, plan adherence and engineer cards',
          description: 'Engineer × week audit of OEE, performance, plan adherence, quality and availability — with Excel and PDF export.',
        },
        {
          title: 'Machine Telemetry',
          subtitle: 'Process variables, shot by shot',
          browserLabel: 'mes.chunil.mx/realtime-data/historical',
          image: portfolioAssets.mesHistorical,
          alt: 'Telemetry variable trends for one injection machine over a full day',
          description: 'Raw cycle process data per machine — cycle time, fill time, dose, cushion and peak pressure with min/max trends and a live mode.',
        },
        {
          title: 'Line Stop History',
          subtitle: 'Downtime review and justification',
          browserLabel: 'mes.chunil.mx/realtime-data/dashboard',
          image: portfolioAssets.mesLineStopHistory,
          alt: 'Line stop history workflow',
          description: 'A workflow to review stop events, inspect downtime detail and support justification.',
        },
        {
          title: 'Injection Data',
          subtitle: 'OEE, quality and process detail',
          browserLabel: 'mes.chunil.mx/injection/injection-data',
          image: portfolioAssets.mesInjectionData,
          alt: 'Injection data dashboard with OEE and production records',
          description: 'Availability, performance, quality and OEE with full production records and process variables.',
        },
        {
          title: 'Assembly Data (Live)',
          subtitle: 'Manual + semiauto in one report',
          browserLabel: 'mes.chunil.mx/assembly/assembly-data-live',
          image: portfolioAssets.mesAssemblyData,
          alt: 'Assembly data dashboard with live OEE and production records',
          description: 'Scanners and semiautomatic machines unified in one live report — OEE, OK/NG counts, downtime and operators per line.',
        },
        {
          title: 'EPC Production',
          subtitle: 'Records, PPM and defects',
          browserLabel: 'mes.chunil.mx/epc/epc-data',
          image: portfolioAssets.mesEpcData,
          alt: 'EPC production records dashboard',
          description: 'Millions of pieces tracked with OK/NG breakdown, defect rate and PPM by part and customer.',
        },
        {
          title: 'Preventive Maintenance Status',
          subtitle: 'Tooling runtime and PM visibility',
          browserLabel: 'mes.chunil.mx/tooling/molds/pm-runtime',
          image: portfolioAssets.toolingPm,
          alt: 'Tooling preventive maintenance dashboard',
          description: 'A tooling dashboard that highlights runtime, overdue molds and preventive maintenance status.',
        },
        {
          title: 'Mold Tracking',
          subtitle: 'Tooling follow-up',
          browserLabel: 'mes.chunil.mx/tooling/molds/mold-tracking',
          image: portfolioAssets.moldTracking,
          alt: 'Mold tracking system',
          description: 'A tooling view to track ownership, progress, dates and problem status.',
        },
        {
          title: 'Maintenance Orders',
          subtitle: 'Corrective and preventive execution',
          browserLabel: 'mes.chunil.mx/tooling/maintenance/order',
          image: portfolioAssets.moldMaintenanceOrders,
          alt: 'Tooling maintenance orders dashboard',
          description: 'An order management view for tooling requests, maintenance type and problem detail.',
        },
        {
          title: 'Regrind / Grinder Data',
          subtitle: 'Scrap regrind inventory & flow',
          browserLabel: 'mes.chunil.mx/injection/data/regrind',
          image: portfolioAssets.mesRegrind,
          alt: 'Grinder data and regrind inventory dashboard',
          description: 'Regrind inventory, grinder output and extruder consumption traced by part, material and shift.',
        },
        {
          title: 'Quality / Quarantine',
          subtitle: 'Top defects and quarantine control',
          browserLabel: 'mes.chunil.mx/quality-management/quarantine',
          image: portfolioAssets.mesQuarantine,
          alt: 'Quarantine quality dashboard with top defects',
          description: 'Top defects overall plus quarantine inventory control for injection and assembly.',
        },
        {
          title: 'Document Control (QMS)',
          subtitle: '5-level document pyramid',
          browserLabel: 'mes.chunil.mx/quality-management/documents',
          image: portfolioAssets.mesDocumentControl,
          alt: 'Quality document control repository',
          description: 'Central QMS repository with reviewer-approved versioning across thousands of controlled documents.',
        },
      ],
    },
    erp: {
      eyebrow: 'ERP-System',
      title: 'An ERP that connects the back office to the floor',
      description:
        'Production planning, HR incidences, warehouse, finances and purchasing — sharing the same database and identity as the MES, so the plant and the office see one truth.',
      gallery: [
        {
          title: 'ERP Home',
          subtitle: 'Module navigation',
          browserLabel: 'erp.chunil.mx/home',
          image: portfolioAssets.erpHome,
          alt: 'ERP home with module access',
          description: 'Single sign-on entry to planning, HR, warehouse, finances and purchasing.',
        },
        {
          title: 'Injection Planning',
          subtitle: 'Weekly plan with formal revisions',
          browserLabel: 'erp.chunil.mx/production-plan/injection',
          image: portfolioAssets.erpProductionPlan,
          alt: 'ERP injection planning timeline with drafts and revisions',
          description: 'Weekly machine × day planning timeline with drafts, formal revisions, overtime toggles and one-click publishing to the MES.',
        },
        {
          title: 'HR Incidences',
          subtitle: 'Capture, review & approval',
          browserLabel: 'erp.chunil.mx/rh/incidencias',
          image: portfolioAssets.erpHrIncidencias,
          alt: 'ERP HR incidence management screen',
          description: 'Structured incidence flow with KPI cards, approval states, time-bank logic and time-clock integration — desktop and mobile.',
        },
        {
          title: 'Warehouse',
          subtitle: 'Resin & material inventory',
          browserLabel: 'erp.chunil.mx/warehouse',
          image: portfolioAssets.erpWarehouse,
          alt: 'ERP warehouse workspace selector',
          description: 'Inventory across raw resin, subsidiaries, regrind and a shared material master with labeling.',
        },
        {
          title: 'Finance Dashboard',
          subtitle: 'Income vs. expenses, live',
          browserLabel: 'erp.chunil.mx/finances',
          image: portfolioAssets.erpFinances,
          alt: 'ERP finance dashboard with income versus expenses by month',
          description: 'Official accounting on a read-only CONTPAQi mirror — income vs. expenses by month, result bridge and year-over-year comparison.',
        },
        {
          title: 'Sales · CFDI',
          subtitle: 'Invoicing mirror from CONTPAQi',
          browserLabel: 'erp.chunil.mx/finances/ventas',
          image: portfolioAssets.erpSales,
          alt: 'ERP sales panel with CFDI invoicing KPIs and weekly chart',
          description: 'Every stamped CFDI mirrored read-only — invoiced, collected and receivables with weekly billing trends by series and customer.',
        },
        {
          title: 'Trial Balance',
          subtitle: 'Workbook upload & mapping',
          browserLabel: 'erp.chunil.mx/finances/reports/trial-balance',
          image: portfolioAssets.erpTrialBalance,
          alt: 'ERP trial balance conversion screen',
          description: 'Drop a standard trial-balance workbook and get a mapped, structured breakdown ready to report.',
        },
      ],
    },
    scanner: {
      eyebrow: 'Mobile · Inventory Scanner',
      title: 'A barcode scanner app for the warehouse',
      description:
        'A React Native (Expo) companion app that puts inventory in the operator’s hand — scanning resin and subsidiary materials straight into the same ERP database.',
      footnote: 'Built with React Native + Expo · one of a family of plant scanner apps (inventory, assembly, EPC, quality) sharing the same identity and database.',
      gallery: [
        {
          title: 'Warehouse overview',
          subtitle: 'Live totals in the operator’s hand',
          image: portfolioAssets.scannerHome,
          alt: 'Scanner app overview with warehouse, blocked and consumed totals',
          description: 'Opening screen with stock on hand, blocked material, production and consumption for the period, per material.',
        },
        {
          title: 'Inventory menu',
          subtitle: 'Materials by category',
          image: portfolioAssets.scannerInventario,
          alt: 'Scanner app inventory menu',
          description: 'Raw resin and subsidiary materials, each with stock, lots, movements and events.',
        },
        {
          title: 'Stock & handling units',
          subtitle: 'Every HU, lot and location',
          image: portfolioAssets.scannerStock,
          alt: 'Scanner app stock screen listing handling units by status',
          description: 'Active handling units split by released, pending inspection and blocked — each with its lot, quantity and location.',
        },
        {
          title: 'Lots & quality status',
          subtitle: 'Release control per lot',
          image: portfolioAssets.scannerLotes,
          alt: 'Scanner app lot list with quality and release status',
          description: 'Lot-level traceability with quality decision, release state and cycle status before material can be used.',
        },
        {
          title: 'Raw material',
          subtitle: 'Resin flows',
          image: portfolioAssets.scannerResinas,
          alt: 'Scanner app raw material inventory',
          description: 'Counts, receipts from inbound and movements for base resin materials.',
        },
        {
          title: 'Subsidiary material',
          subtitle: 'Components and consumables',
          image: portfolioAssets.scannerSubsidiarios,
          alt: 'Scanner app subsidiary material inventory',
          description: 'The same stock, lot and movement flows for subsidiary materials and consumables.',
        },
        {
          title: 'Activity centre',
          subtitle: 'Who moved what, and when',
          image: portfolioAssets.scannerNotificaciones,
          alt: 'Scanner app notification centre with recent inventory activity',
          description: 'Push notifications for transfers, contextual process returns and quality decisions, each stamped with the operator.',
        },
        {
          title: 'Roles & permissions',
          subtitle: 'Access-aware by design',
          image: portfolioAssets.scannerAdmin,
          alt: 'Scanner app profile screen with roles and permissions',
          description: 'Every screen is gated by the roles and permissions the ERP grants the signed-in user.',
        },
      ],
    },
    analytics: {
      eyebrow: 'Analytics',
      title: 'The analysis leadership reads every Monday',
      description:
        'The same manufacturing data becomes a written weekly production report and review-ready Power BI dashboards — plan adherence, lost time and quality, explained rather than dumped.',
      gallery: [
        {
          title: 'Weekly Production Report',
          subtitle: 'Written for directors, not for analysts',
          image: portfolioAssets.weeklyReportSummary,
          alt: 'Weekly production report cover page with plan adherence KPIs and key findings',
          description: 'A 17-page report generated every Monday: headline adherence, lost time, quality and overtime, plus key findings that name the exact part, machine and cause behind each miss.',
        },
        {
          title: 'Six-Week Adherence View',
          subtitle: 'Reconciled per part, week over week',
          image: portfolioAssets.weeklyReportTrend,
          alt: 'Six-week planned versus achieved chart from the weekly production report',
          description: 'Planned vs. achieved per week with adherence reconciled part by part — overproduction never offsets a miss, and prior weeks restate as quality keeps filing.',
        },
        {
          title: 'Plan Adherence Review',
          subtitle: 'Planned vs. achieved, weekly',
          image: portfolioAssets.powerbiPlan,
          alt: 'Power BI plan adherence dashboard',
          description: 'Planned, achieved, not-produced and overproduction with adherence and quality at a glance.',
        },
        {
          title: 'Performance Drivers',
          subtitle: 'Where the gaps come from',
          image: portfolioAssets.powerbiDrivers,
          alt: 'Power BI performance drivers dashboard',
          description: 'Top not-produced and overproduced pieces by part and customer to target the real drivers.',
        },
      ],
    },
    support: {
      eyebrow: 'How I work',
      title: 'Where I create the most value',
      description:
        'I create the most value where operations, industrial data and software delivery have to move together.',
      items: [
        {
          title: 'MES & Industrial IoT',
          text: 'I connect machines, plant logic and user workflows into systems operations can use every shift.',
        },
        {
          title: 'Operational dashboards',
          text: 'I build real-time screens that are readable, useful and aligned with daily plant decisions.',
        },
        {
          title: 'Data engineering & ETL',
          text: 'I design databases, pipelines and business rules that make manufacturing data reliable.',
        },
        {
          title: 'Power BI & automation',
          text: 'I turn raw data into recurring reports and management dashboards that are ready to review.',
        },
      ],
    },
    experience: {
      eyebrow: 'Experience',
      title: 'Built in real operation',
      description: 'Manufacturing execution, data engineering and analytics tied to business outcomes.',
      items: [
        {
          company: 'Chunil Mexico',
          role: 'Data Engineer · MES & Manufacturing Analytics',
          period: 'Oct 2024 — Present',
          summary:
            'Designed and shipped a production MES and ERP for a plastic-injection plant: industrial integration, backend services, analytics and React apps for shopfloor teams.',
          bullets: [
            'Centralized injection, assembly, EPC, tooling and plant operations in one web platform.',
            'Integrated 34 machines into real-time dashboards, historical analysis and downtime logic.',
            'Recognized as Department Employee of the Year.',
          ],
        },
        {
          company: 'Ramirez Valle & Asociados · General Motors SLP',
          role: 'Claims, Loss & Recovery Coordinator',
          period: 'Oct 2023 — 2024',
          summary:
            'Operational analytics focused on financial recovery, evidence management and executive visibility.',
          bullets: [
            'Led data-driven logistics claims analysis and financial recovery.',
            'Built Power BI dashboards that cut analysis time by 40%.',
            'Structured evidence and tracking workflows for 100+ cases.',
          ],
        },
      ],
    },
    recognition: {
      eyebrow: 'Recognition & training',
      title: 'The background behind the work',
      publicationLabel: 'View on LinkedIn',
      items: [
        {
          title: 'Department Employee of the Year',
          kicker: 'Recognition',
          text: 'Recognized at Chunil Mexico for discipline, execution and measurable contribution.',
          image: portfolioAssets.award,
          alt: 'Department Employee of the Year recognition',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'KeepCoding',
          kicker: 'Advanced training',
          text: 'Big Data, AI, Machine Learning and full-stack training applied to real delivery.',
          image: portfolioAssets.keepCoding,
          alt: 'KeepCoding certification',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'General Motors SLP',
          kicker: 'Business exposure',
          text: 'Operational analytics, claims recovery and executive visibility in an industrial environment.',
          image: portfolioAssets.gm,
          alt: 'General Motors San Luis Potosí team',
          publicationUrl: contactLinks.linkedin,
        },
      ],
    },
    extraProjects: {
      eyebrow: 'Bootcamp Projects',
      title: 'Extra work from KeepCoding',
      description: 'Selected projects from my KeepCoding Web Development Bootcamp repository — from JavaScript foundations to a fully tested REST API.',
      linkLabel: 'Open on GitHub',
      items: [
        {
          title: 'BookShop REST API',
          kicker: 'Node · TypeScript · Prisma · PostgreSQL',
          text: 'Second-hand book marketplace API built with strict hexagonal architecture: JWT auth, domain events that email the seller on a sale, a weekly cron that suggests price drops, and 8 end-to-end tests passing against a real database.',
          image: portfolioAssets.bootcampBookshop,
          alt: 'Newman report showing the BookShop API end-to-end test suite passing',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/08_backend-avanzado-js/02_final_test',
        },
        {
          title: 'React Product Dashboard',
          kicker: 'React 19 · TypeScript · React Router · Vite',
          text: 'Single-page catalog and CRUD for retro consoles and classic games: token login with protected routes, name and offer filters, product detail, controlled creation forms, image upload and a two-step delete confirmation.',
          image: portfolioAssets.bootcampReactDashboard,
          alt: 'React product dashboard listing retro consoles with filters',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/07_react-fundamentos/02_final_test',
        },
        {
          title: 'Streambox Landing Page',
          kicker: 'HTML5 · SCSS · Vanilla JS',
          text: 'Streaming-style landing page with semantic structure, catalog rows and an interactive spotlight that updates synopsis and trailer from local data.',
          image: portfolioAssets.bootcampStreambox,
          alt: 'Streambox streaming landing page project',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/03_html-css_fundamentals/00_final-test',
        },
        {
          title: 'Videoclub SQL Modeling',
          kicker: 'PostgreSQL · ERD · SQL Scripts',
          text: 'Normalized video-rental database with ERD, schema scripts, insert pipeline and validation queries for members, inventory, rentals and availability.',
          image: portfolioAssets.bootcampSql,
          alt: 'Videoclub SQL modeling entity relationship diagram',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/02_sql_modeling/02_final_test',
        },
        {
          title: 'JavaScript Foundations Practice',
          kicker: 'JavaScript · Async · Data Transformations',
          text: 'Practice bundle covering bug fixing, array transformations, promises and async/await as the first step into modern frontend logic.',
          image: portfolioAssets.bootcampJs,
          alt: 'JavaScript foundations module artwork',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/01_intro-javascript/practica_final',
        },
      ],
    },
    education: {
      eyebrow: 'Education',
      title: 'Training and core stack',
      description: 'Academic and technical background applied to manufacturing and analytics.',
      educationTitle: 'Education',
      stackTitle: 'Core stack',
      languagesTitle: 'Languages',
      items: [
        'Full Stack Web Development Bootcamp, KeepCoding · Nov 2025 — Present',
        'Business Analytics, Tecnológico de Monterrey · Jan 2025 — Apr 2025',
        'Big Data, AI & Machine Learning Bootcamp, KeepCoding · Jun 2023 — Jun 2024',
        'Python for Data Science, IICO · May 2022 — Aug 2022',
        'BA in Economics, UASLP · Aug 2018 — Jul 2023',
        'Industrial & Logistics Engineering, UNID · Aug 2014 — Jul 2017',
      ],
      stack: [
        'PostgreSQL', 'SQL', 'Node.js', 'React', 'Vite', 'REST APIs',
        'Socket.IO', 'ETL', 'Power BI', 'OEE', 'Modbus', 'EUROMAP63',
      ],
      languages: ['Spanish — Native', 'English — Professional working proficiency'],
    },
    closing: {
      eyebrow: 'Available for collaboration',
      title: 'If your operation needs to run on better systems, that is exactly where I fit.',
      description:
        'Independent or in-house — I can lead MES, Industrial IoT, dashboards, Power BI, reporting automation and connected manufacturing applications.',
      primary: 'Email me',
      quaternary: 'LinkedIn',
    },
    footer: {
      role: 'Data Engineer · Industrial IoT · Manufacturing Systems',
      builtWith: 'Built with React + Vite + Framer Motion',
    },
  },

  es: {
    brandRole: 'Data Engineer · MES · Industrial IoT',
    imageZoomLabel: 'Abrir imagen',
    imageCloseLabel: 'Cerrar vista de imagen',
    navigation: [
      { label: 'Impacto', href: '#impact' },
      { label: 'MES', href: '#mes' },
      { label: 'ERP', href: '#erp' },
      { label: 'Scanner', href: '#scanner' },
      { label: 'Analítica', href: '#analytics' },
      { label: 'Experiencia', href: '#experience' },
      { label: 'Contacto', href: '#contact' },
    ],
    languageSwitchLabel: 'Seleccionar idioma',
    cvLabel: 'Descargar CV',
    githubLabel: 'GitHub',
    hero: {
      eyebrow: 'Data Engineer · Sistemas de manufactura',
      titleLead: 'Construyo sistemas de manufactura que vuelven los',
      titleAccent: 'datos en vivo en control diario.',
      description:
        'Soy Juan Roberto García Gómez. Diseño y entrego el software con el que opera una planta: un MES en tiempo real, un ERP, integración de IoT industrial y la analítica que la dirección revisa cada mañana.',
      primaryAction: 'Ver los sistemas',
      secondaryAction: 'Descargar CV',
      linkedin: 'LinkedIn',
      portraitAlt: 'Foto profesional de Juan Roberto García Gómez',
      focusTitle: 'Lo que entrego de inicio a fin',
      focusItems: [
        'Dashboards MES en tiempo real para shopfloor y dirección',
        'Módulos de producción, paros, calidad, tooling y planeación en uso diario',
        'Integración de máquinas, pipelines ETL y Power BI sobre MES + ERP',
      ],
    },
    impact: {
      eyebrow: 'Impacto',
      title: 'Resultados, no solo pantallas',
      description:
        'Cada número proviene de sistemas en producción en una planta de inyección de plástico en San Luis Potosí.',
      stats: [
        {
          value: '34',
          label: 'máquinas conectadas',
          detail: 'Integración EUROMAP63 y Modbus en máquinas de inyección ENGEL, WOOJIN y SUMITOMO — más 14 estaciones semiautomáticas y todas las estaciones manuales de ensamble en vivo.',
        },
        {
          value: '90%',
          label: 'menos captura manual',
          detail: 'La producción llega en tiempo real; el equipo solo agrega contexto de paros y defectos.',
        },
        {
          value: '24/7',
          label: 'visibilidad del plan',
          detail: 'La dirección ve plan vs. real, causas de paro y producción corriendo sin plan, en vivo.',
        },
        {
          value: '6',
          label: 'áreas de planta unificadas',
          detail: 'Inyección, ensamble, EPC, tooling, calidad y mantenimiento en una sola plataforma MES + ERP.',
        },
      ],
    },
    mes: {
      eyebrow: 'Sistema principal · MES-System',
      title: 'Un MES en tiempo real con el que opera la planta',
      description:
        'Una plataforma web que centraliza inyección, ensamble, EPC, tooling, calidad y datos de máquina en vivo — hecha con React y Node.js, sobre PostgreSQL.',
      featured: {
        title: 'Live Stop Board y estado de máquinas',
        subtitle: 'Control de shopfloor en tiempo real',
        browserLabel: 'mes.chunil.mx/realtime-data/dashboard',
        image: portfolioAssets.mesRealtime,
        alt: 'Dashboard MES en tiempo real con el estado de todas las máquinas de la planta',
        text: 'Una sola pantalla operativa con el estado de cada máquina, el stop board en vivo y las excepciones del plan — para reaccionar en el momento en que cambia la producción durante el turno.',
        metrics: [
          { value: '34', label: 'máquinas en vivo' },
          { value: '3', label: 'turnos/día' },
          { value: 'Socket.IO', label: 'feed en tiempo real' },
          { value: 'React + Node', label: 'full stack' },
        ],
      },
      galleryTitle: 'Dentro del MES',
      galleryDescription: 'Módulos centrales usados en inyección, tooling, calidad y EPC cada turno.',
      gallery: [
        {
          title: 'Home de módulos',
          subtitle: 'Punto de entrada unificado',
          browserLabel: 'mes.chunil.mx/home',
          image: portfolioAssets.mesHome,
          alt: 'Home del MES con acceso a cada módulo',
          description: 'Pantalla principal por rol con acceso directo a cada módulo y contexto en vivo.',
        },
        {
          title: 'Ensamble en vivo — Estaciones manuales',
          subtitle: 'Cada estación, cada turno, en vivo',
          browserLabel: 'mes.chunil.mx/realtime-data/assembly/dashboard',
          image: portfolioAssets.mesAssemblyRealtime,
          alt: 'Dashboard en vivo de ensamble con una card por estación manual',
          description: 'Una card en vivo por estación manual — parte, operador, timers de run/stop, cajas y avance contra el plan del turno.',
        },
        {
          title: 'Estaciones semiautomáticas',
          subtitle: 'Leak testers directo del PLC',
          browserLabel: 'mes.chunil.mx/realtime-data/assembly/semiauto',
          image: portfolioAssets.mesSemiautoRealtime,
          alt: 'Dashboard en vivo de estaciones semiautomáticas de prueba de fuga',
          description: 'Leak testers y máquinas semiautomáticas transmitiendo contadores del PLC en vivo, con causas de paro y alertas de justificación pendiente.',
        },
        {
          title: 'Cobertura de embarques EPC',
          subtitle: 'Inventario vs. forecast a 8 semanas',
          browserLabel: 'mes.chunil.mx/realtime-data/epc-coverage',
          image: portfolioAssets.mesEpcCoverage,
          alt: 'Tabla de cobertura EPC de inventario contra forecast por semana',
          description: 'Cobertura en vivo del inventario contra el forecast del cliente por parte — marcando la semana exacta en que cada parte se agota.',
        },
        {
          title: 'Shift Analytics',
          subtitle: 'Auditoría de OEE por ingeniero y semana',
          browserLabel: 'mes.chunil.mx/realtime-data/shift-analytics',
          image: portfolioAssets.mesShiftAnalytics,
          alt: 'Dashboard de Shift Analytics con OEE, adherencia al plan y cards por ingeniero',
          description: 'Auditoría ingeniero × semana de OEE, performance, adherencia al plan, calidad y disponibilidad — con export a Excel y PDF.',
        },
        {
          title: 'Telemetría de máquina',
          subtitle: 'Variables de proceso, disparo a disparo',
          browserLabel: 'mes.chunil.mx/realtime-data/historical',
          image: portfolioAssets.mesHistorical,
          alt: 'Tendencias de variables de telemetría de una máquina de inyección en un día completo',
          description: 'Datos crudos de proceso por máquina — tiempo ciclo, fill time, dosificación, cushion y presión pico con tendencias min/max y modo en vivo.',
        },
        {
          title: 'Historial de paros de línea',
          subtitle: 'Revisión y justificación de downtime',
          browserLabel: 'mes.chunil.mx/realtime-data/dashboard',
          image: portfolioAssets.mesLineStopHistory,
          alt: 'Flujo de historial de paros de línea',
          description: 'Flujo para revisar eventos de paro, ver detalle del downtime y soportar la justificación.',
        },
        {
          title: 'Injection Data',
          subtitle: 'OEE, calidad y detalle de proceso',
          browserLabel: 'mes.chunil.mx/injection/injection-data',
          image: portfolioAssets.mesInjectionData,
          alt: 'Dashboard de injection data con OEE y registros de producción',
          description: 'Disponibilidad, desempeño, calidad y OEE con registros completos y variables de proceso.',
        },
        {
          title: 'Assembly Data (Live)',
          subtitle: 'Manual + semiauto en un solo reporte',
          browserLabel: 'mes.chunil.mx/assembly/assembly-data-live',
          image: portfolioAssets.mesAssemblyData,
          alt: 'Dashboard de assembly data con OEE y registros en vivo',
          description: 'Scanners y máquinas semiautomáticas unificados en un reporte en vivo — OEE, conteos OK/NG, downtime y operadores por línea.',
        },
        {
          title: 'Producción EPC',
          subtitle: 'Registros, PPM y defectos',
          browserLabel: 'mes.chunil.mx/epc/epc-data',
          image: portfolioAssets.mesEpcData,
          alt: 'Dashboard de registros de producción EPC',
          description: 'Millones de piezas con desglose OK/NG, tasa de defecto y PPM por parte y cliente.',
        },
        {
          title: 'Estado de mantenimiento preventivo',
          subtitle: 'Runtime de tooling y visibilidad de PM',
          browserLabel: 'mes.chunil.mx/tooling/molds/pm-runtime',
          image: portfolioAssets.toolingPm,
          alt: 'Dashboard de mantenimiento preventivo de tooling',
          description: 'Dashboard de tooling para ver runtime, moldes vencidos y estado de mantenimiento preventivo.',
        },
        {
          title: 'Mold Tracking',
          subtitle: 'Seguimiento de tooling',
          browserLabel: 'mes.chunil.mx/tooling/molds/mold-tracking',
          image: portfolioAssets.moldTracking,
          alt: 'Sistema de Mold Tracking',
          description: 'Vista para controlar responsables, avance, fechas y estado de problemas de tooling.',
        },
        {
          title: 'Órdenes de mantenimiento',
          subtitle: 'Ejecución correctiva y preventiva',
          browserLabel: 'mes.chunil.mx/tooling/maintenance/order',
          image: portfolioAssets.moldMaintenanceOrders,
          alt: 'Dashboard de órdenes de mantenimiento de tooling',
          description: 'Vista para gestionar solicitudes de tooling, tipo de mantenimiento y detalle del problema.',
        },
        {
          title: 'Regrind / Grinder Data',
          subtitle: 'Inventario y flujo de regrind',
          browserLabel: 'mes.chunil.mx/injection/data/regrind',
          image: portfolioAssets.mesRegrind,
          alt: 'Dashboard de grinder data e inventario de regrind',
          description: 'Inventario de regrind, salida de molino y consumo de extrusor por parte, material y turno.',
        },
        {
          title: 'Calidad / Cuarentena',
          subtitle: 'Top de defectos y control de cuarentena',
          browserLabel: 'mes.chunil.mx/quality-management/quarantine',
          image: portfolioAssets.mesQuarantine,
          alt: 'Dashboard de calidad y cuarentena con top de defectos',
          description: 'Top de defectos general y control de inventario en cuarentena para inyección y ensamble.',
        },
        {
          title: 'Control de documentos (QMS)',
          subtitle: 'Pirámide documental de 5 niveles',
          browserLabel: 'mes.chunil.mx/quality-management/documents',
          image: portfolioAssets.mesDocumentControl,
          alt: 'Repositorio de control de documentos de calidad',
          description: 'Repositorio QMS central con versionado aprobado por revisor sobre miles de documentos controlados.',
        },
      ],
    },
    erp: {
      eyebrow: 'ERP-System',
      title: 'Un ERP que conecta el back office con el piso',
      description:
        'Planeación de producción, incidencias de RH, almacén, finanzas y compras — compartiendo la misma base de datos e identidad que el MES, para que planta y oficina vean una sola verdad.',
      gallery: [
        {
          title: 'Home del ERP',
          subtitle: 'Navegación de módulos',
          browserLabel: 'erp.chunil.mx/home',
          image: portfolioAssets.erpHome,
          alt: 'Home del ERP con acceso a módulos',
          description: 'Entrada con sesión única a planeación, RH, almacén, finanzas y compras.',
        },
        {
          title: 'Planificación de inyección',
          subtitle: 'Plan semanal con revisiones formales',
          browserLabel: 'erp.chunil.mx/production-plan/injection',
          image: portfolioAssets.erpProductionPlan,
          alt: 'Timeline de planificación de inyección del ERP con borradores y revisiones',
          description: 'Timeline semanal máquina × día con borradores, revisiones formales, tiempo extra y publicación al MES con un clic.',
        },
        {
          title: 'Incidencias RH',
          subtitle: 'Captura, revisión y aprobación',
          browserLabel: 'erp.chunil.mx/rh/incidencias',
          image: portfolioAssets.erpHrIncidencias,
          alt: 'Pantalla de gestión de incidencias de RH del ERP',
          description: 'Flujo de incidencias con KPI cards, estados de aprobación, banco de tiempo y conexión al reloj checador — desktop y móvil.',
        },
        {
          title: 'Almacén',
          subtitle: 'Inventario de resina y material',
          browserLabel: 'erp.chunil.mx/warehouse',
          image: portfolioAssets.erpWarehouse,
          alt: 'Selector de áreas de trabajo de almacén del ERP',
          description: 'Inventario de resina, subsidiarios, regrind y un maestro de materiales compartido con etiquetado.',
        },
        {
          title: 'Dashboard de finanzas',
          subtitle: 'Ingresos vs. egresos, en vivo',
          browserLabel: 'erp.chunil.mx/finances',
          image: portfolioAssets.erpFinances,
          alt: 'Dashboard de finanzas del ERP con ingresos contra egresos por mes',
          description: 'Contabilidad oficial sobre espejo de CONTPAQi solo lectura — ingresos vs. egresos por mes, puente de resultado y comparativo contra el año anterior.',
        },
        {
          title: 'Ventas · CFDI',
          subtitle: 'Espejo de facturación desde CONTPAQi',
          browserLabel: 'erp.chunil.mx/finances/ventas',
          image: portfolioAssets.erpSales,
          alt: 'Panel de ventas del ERP con KPIs de facturación CFDI y gráfica semanal',
          description: 'Cada CFDI timbrado espejado solo lectura — facturado, cobrado y por cobrar con tendencia semanal de facturación por serie y cliente.',
        },
        {
          title: 'Balanza de comprobación',
          subtitle: 'Carga y mapeo de workbook',
          browserLabel: 'erp.chunil.mx/finances/reports/trial-balance',
          image: portfolioAssets.erpTrialBalance,
          alt: 'Pantalla de conversión de balanza de comprobación del ERP',
          description: 'Sube una balanza estándar y obtén un desglose mapeado y estructurado listo para reportar.',
        },
      ],
    },
    scanner: {
      eyebrow: 'Móvil · Inventory Scanner',
      title: 'Una app de escaneo para el almacén',
      description:
        'Una app complementaria en React Native (Expo) que pone el inventario en la mano del operador — escaneando resina y material subsidiario directo a la misma base de datos del ERP.',
      footnote: 'Hecha con React Native + Expo · una de una familia de apps de escaneo de planta (inventario, ensamble, EPC, calidad) con la misma identidad y base de datos.',
      gallery: [
        {
          title: 'Panorama del almacén',
          subtitle: 'Totales en vivo en la mano del operador',
          image: portfolioAssets.scannerHome,
          alt: 'Pantalla principal de la app con totales de almacén, bloqueado y consumido',
          description: 'Pantalla de entrada con existencias, material bloqueado, producción y consumo del periodo, material por material.',
        },
        {
          title: 'Menú de inventario',
          subtitle: 'Materiales por categoría',
          image: portfolioAssets.scannerInventario,
          alt: 'Menú de inventario de la app de escaneo',
          description: 'Materia prima y subsidiarios, cada uno con stock, lotes, movimientos y eventos.',
        },
        {
          title: 'Stock y handling units',
          subtitle: 'Cada HU, lote y ubicación',
          image: portfolioAssets.scannerStock,
          alt: 'Pantalla de stock de la app con handling units por estado',
          description: 'Handling units activas separadas por liberadas, pendientes de inspección y bloqueadas — cada una con su lote, cantidad y ubicación.',
        },
        {
          title: 'Lotes y estado de calidad',
          subtitle: 'Control de liberación por lote',
          image: portfolioAssets.scannerLotes,
          alt: 'Listado de lotes de la app con estado de calidad y liberación',
          description: 'Trazabilidad a nivel lote con decisión de calidad, estado de liberación y ciclo antes de que el material pueda usarse.',
        },
        {
          title: 'Materia prima',
          subtitle: 'Flujos de resina',
          image: portfolioAssets.scannerResinas,
          alt: 'Inventario de materia prima de la app',
          description: 'Conteos, entradas desde recibo y movimientos para materiales base de resina.',
        },
        {
          title: 'Material subsidiario',
          subtitle: 'Componentes y consumibles',
          image: portfolioAssets.scannerSubsidiarios,
          alt: 'Inventario de material subsidiario de la app',
          description: 'Los mismos flujos de stock, lotes y movimientos para materiales subsidiarios y consumibles.',
        },
        {
          title: 'Centro de actividad',
          subtitle: 'Quién movió qué, y cuándo',
          image: portfolioAssets.scannerNotificaciones,
          alt: 'Centro de notificaciones de la app con la actividad reciente de inventario',
          description: 'Notificaciones push de transferencias, retornos contextuales de proceso y decisiones de calidad, cada una firmada por el operador.',
        },
        {
          title: 'Roles y permisos',
          subtitle: 'Acceso controlado por diseño',
          image: portfolioAssets.scannerAdmin,
          alt: 'Pantalla de perfil de la app con roles y permisos',
          description: 'Cada pantalla se habilita según los roles y permisos que el ERP le otorga al usuario con sesión activa.',
        },
      ],
    },
    analytics: {
      eyebrow: 'Analítica',
      title: 'El análisis que la dirección lee cada lunes',
      description:
        'Los mismos datos de manufactura se vuelven un reporte semanal de producción escrito y dashboards de Power BI listos para revisión — adherencia al plan, tiempo perdido y calidad, explicados en vez de volcados.',
      gallery: [
        {
          title: 'Reporte semanal de producción',
          subtitle: 'Escrito para dirección, no para analistas',
          image: portfolioAssets.weeklyReportSummary,
          alt: 'Portada del reporte semanal de producción con KPIs de adherencia al plan y hallazgos clave',
          description: 'Un reporte de 17 páginas generado cada lunes: adherencia, tiempo perdido, calidad y tiempo extra, más hallazgos que nombran la parte, la máquina y la causa exacta detrás de cada faltante.',
        },
        {
          title: 'Vista de seis semanas',
          subtitle: 'Reconciliada por parte, semana a semana',
          image: portfolioAssets.weeklyReportTrend,
          alt: 'Gráfica de seis semanas de plan contra logrado del reporte semanal de producción',
          description: 'Plan vs. logrado por semana con la adherencia reconciliada parte por parte — la sobreproducción nunca compensa un faltante, y las semanas previas se recalculan conforme Calidad sigue capturando.',
        },
        {
          title: 'Revisión de adherencia',
          subtitle: 'Plan vs. logrado, semanal',
          image: portfolioAssets.powerbiPlan,
          alt: 'Dashboard Power BI de adherencia al plan',
          description: 'Plan, logrado, no producido y sobreproducción con adherencia y calidad de un vistazo.',
        },
        {
          title: 'Drivers de desempeño',
          subtitle: 'De dónde vienen las brechas',
          image: portfolioAssets.powerbiDrivers,
          alt: 'Dashboard Power BI de drivers de desempeño',
          description: 'Top de piezas no producidas y sobreproducidas por parte y cliente para atacar los drivers reales.',
        },
      ],
    },
    support: {
      eyebrow: 'Cómo trabajo',
      title: 'Dónde genero más valor',
      description:
        'Genero más valor donde operación, datos industriales y entrega de software deben avanzar juntos.',
      items: [
        {
          title: 'MES e Industrial IoT',
          text: 'Conecto máquinas, lógica de planta y flujos de usuario en sistemas que operación usa cada turno.',
        },
        {
          title: 'Dashboards operativos',
          text: 'Construyo vistas en tiempo real claras, útiles y alineadas con decisiones de planta.',
        },
        {
          title: 'Data engineering y ETL',
          text: 'Diseño bases de datos, pipelines y reglas de negocio que vuelven confiables los datos de manufactura.',
        },
        {
          title: 'Power BI y automatización',
          text: 'Convierto datos crudos en reportes recurrentes y dashboards gerenciales listos para revisión.',
        },
      ],
    },
    experience: {
      eyebrow: 'Experiencia',
      title: 'Construido en operación real',
      description: 'Manufactura, data engineering y analítica orientada a resultados de negocio.',
      items: [
        {
          company: 'Chunil Mexico',
          role: 'Data Engineer · MES & Manufacturing Analytics',
          period: 'Oct 2024 — Actualidad',
          summary:
            'Diseñé y entregué un MES y un ERP productivos para una planta de inyección: integración industrial, backend, analítica y apps React para shopfloor.',
          bullets: [
            'Centralicé inyección, ensamble, EPC, tooling y operación de planta en una sola plataforma web.',
            'Integré 34 máquinas a dashboards en tiempo real, análisis histórico y lógica de downtime.',
            'Reconocido como Mejor Empleado del Departamento del Año.',
          ],
        },
        {
          company: 'Ramirez Valle & Asociados · General Motors SLP',
          role: 'Claims, Loss & Recovery Coordinator',
          period: 'Oct 2023 — 2024',
          summary:
            'Analítica operativa enfocada en recuperación financiera, gestión de evidencia y visibilidad ejecutiva.',
          bullets: [
            'Lideré análisis data-driven de claims logísticos y recuperación financiera.',
            'Construí dashboards Power BI que redujeron 40% el tiempo de análisis.',
            'Estructuré flujos de evidencia y seguimiento para más de 100 casos.',
          ],
        },
      ],
    },
    recognition: {
      eyebrow: 'Reconocimiento y formación',
      title: 'La trayectoria detrás del trabajo',
      publicationLabel: 'Ver en LinkedIn',
      items: [
        {
          title: 'Mejor empleado del departamento del año',
          kicker: 'Reconocimiento',
          text: 'Reconocimiento en Chunil Mexico por disciplina, ejecución e impacto medible.',
          image: portfolioAssets.award,
          alt: 'Reconocimiento al mejor empleado del departamento del año',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'KeepCoding',
          kicker: 'Formación avanzada',
          text: 'Bootcamp aplicado a proyectos reales de datos, IA y desarrollo full-stack.',
          image: portfolioAssets.keepCoding,
          alt: 'Certificación de KeepCoding',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'General Motors SLP',
          kicker: 'Experiencia de negocio',
          text: 'Analítica operativa, recuperación de claims y visibilidad ejecutiva en entorno industrial.',
          image: portfolioAssets.gm,
          alt: 'Equipo de General Motors San Luis Potosí',
          publicationUrl: contactLinks.linkedin,
        },
      ],
    },
    extraProjects: {
      eyebrow: 'Proyectos Bootcamp',
      title: 'Extras de KeepCoding',
      description: 'Proyectos seleccionados de mi repositorio del Bootcamp de Desarrollo Web de KeepCoding — desde fundamentos de JavaScript hasta una API REST con pruebas end-to-end.',
      linkLabel: 'Abrir en GitHub',
      items: [
        {
          title: 'API REST BookShop',
          kicker: 'Node · TypeScript · Prisma · PostgreSQL',
          text: 'API de un marketplace de libros de segunda mano con arquitectura hexagonal estricta: autenticación JWT, eventos de dominio que envían correo al vendedor tras una venta, un cron semanal que sugiere bajar precios y 8 pruebas end-to-end pasando contra base de datos real.',
          image: portfolioAssets.bootcampBookshop,
          alt: 'Reporte de Newman con la suite de pruebas end-to-end de la API BookShop en verde',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/08_backend-avanzado-js/02_final_test',
        },
        {
          title: 'Dashboard de productos en React',
          kicker: 'React 19 · TypeScript · React Router · Vite',
          text: 'SPA de catálogo y CRUD de consolas retro y videojuegos clásicos: login con token y rutas protegidas, filtros por nombre y oferta, detalle de producto, formularios controlados de alta, subida de imágenes y borrado con confirmación en dos pasos.',
          image: portfolioAssets.bootcampReactDashboard,
          alt: 'Dashboard de productos en React con el listado de consolas retro y filtros',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/07_react-fundamentos/02_final_test',
        },
        {
          title: 'Landing Page Streambox',
          kicker: 'HTML5 · SCSS · Vanilla JS',
          text: 'Landing page estilo streaming con estructura semántica, filas de catálogo y un spotlight interactivo que actualiza sinopsis y tráiler desde datos locales.',
          image: portfolioAssets.bootcampStreambox,
          alt: 'Proyecto de landing page tipo streaming Streambox',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/03_html-css_fundamentals/00_final-test',
        },
        {
          title: 'Modelado SQL Videoclub',
          kicker: 'PostgreSQL · ERD · Scripts SQL',
          text: 'Base de datos normalizada para un videoclub con diagrama entidad-relación, scripts de esquema, carga de datos y consultas de validación.',
          image: portfolioAssets.bootcampSql,
          alt: 'Diagrama entidad-relación del proyecto SQL Videoclub',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/02_sql_modeling/02_final_test',
        },
        {
          title: 'Prácticas de Fundamentos JavaScript',
          kicker: 'JavaScript · Async · Transformaciones',
          text: 'Conjunto de prácticas con corrección de bugs, transformaciones de arreglos, promesas y async/await como base para la lógica frontend moderna.',
          image: portfolioAssets.bootcampJs,
          alt: 'Arte del módulo de fundamentos de JavaScript',
          projectUrl: 'https://github.com/Robertogag/KeepCoding-Bootcamp-Desarrollo-Web-Edicion-XX/tree/main/01_intro-javascript/practica_final',
        },
      ],
    },
    education: {
      eyebrow: 'Educación',
      title: 'Formación y stack principal',
      description: 'Base académica y técnica aplicada a manufactura y analítica.',
      educationTitle: 'Formación',
      stackTitle: 'Stack principal',
      languagesTitle: 'Idiomas',
      items: [
        'Bootcamp Full Stack Web Development, KeepCoding · Nov 2025 — Actualidad',
        'Business Analytics, Tecnológico de Monterrey · Ene 2025 — Abr 2025',
        'Bootcamp Big Data, AI & Machine Learning, KeepCoding · Jun 2023 — Jun 2024',
        'Python for Data Science, IICO · May 2022 — Ago 2022',
        'Licenciatura en Economía, UASLP · Ago 2018 — Jul 2023',
        'Ingeniería Industrial y Logística, UNID · Ago 2014 — Jul 2017',
      ],
      stack: [
        'PostgreSQL', 'SQL', 'Node.js', 'React', 'Vite', 'REST APIs',
        'Socket.IO', 'ETL', 'Power BI', 'OEE', 'Modbus', 'EUROMAP63',
      ],
      languages: ['Español — Nativo', 'Inglés — Nivel profesional de trabajo'],
    },
    closing: {
      eyebrow: 'Disponible para colaborar',
      title: 'Si tu operación necesita correr sobre mejores sistemas, ahí es exactamente donde encajo.',
      description:
        'Independiente o en empresa — puedo liderar MES, Industrial IoT, dashboards, Power BI, automatización de reportes y aplicaciones conectadas de manufactura.',
      primary: 'Escríbeme',
      quaternary: 'LinkedIn',
    },
    footer: {
      role: 'Data Engineer · Industrial IoT · Sistemas de manufactura',
      builtWith: 'Hecho con React + Vite + Framer Motion',
    },
  },
};
