export const githubLinks = {
  organisation: 'https://github.com/Robertogag',
  mes: 'https://github.com/Chunil-Mexico/MES-System',
  erp: 'https://github.com/Chunil-Mexico/ERP-System',
};

export const contactLinks = {
  email: 'mailto:roberto.gag117@gmail.com',
  emailLabel: 'roberto.gag117@gmail.com',
  linkedin: 'https://www.linkedin.com/in/juan-roberto-garc%C3%ADa-g%C3%B3mez1/',
};

const C = '/assets/images/captures';

export const portfolioAssets = {
  cv: '/assets/docs/juan-roberto-garcia-cv-2026.pdf',
  profile: '/assets/images/roberto-profile-cv2.png',

  // MES captures (fresh, logged in)
  mesHome: `${C}/mes-home.jpg`,
  mesRealtime: `${C}/mes-realtime-dashboard.png`,
  mesInjectionData: `${C}/mes-injection-data.png`,
  mesAssemblyData: `${C}/mes-assembly-data.png`,
  mesEpcData: `${C}/mes-epc-data.png`,
  mesEpcCt: `${C}/mes-epc-ct.png`,
  mesPmRuntime: `${C}/mes-pm-runtime.png`,
  mesMoldTracking: `${C}/mes-mold-tracking.png`,
  mesMaintenanceOrders: `${C}/mes-maintenance-orders.png`,
  mesRegrind: `${C}/mes-regrind.png`,
  mesQuarantine: `${C}/mes-quarantine.png`,
  mesDocumentControl: `${C}/mes-document-control.png`,

  // ERP captures
  erpHome: `${C}/erp-home.jpg`,
  erpProductionPlan: `${C}/erp-production-plan.png`,
  erpHrIncidencias: `${C}/erp-hr-incidencias.png`,
  erpWarehouse: `${C}/erp-warehouse.jpg`,
  erpFinances: `${C}/erp-finances.jpg`,
  erpFinancesMaster: `${C}/erp-finances-master.jpg`,
  erpTrialBalance: `${C}/erp-trial-balance.jpg`,
  erpPurchasing: `${C}/erp-purchasing.png`,

  // Inventory Scanner App (mobile / Expo)
  scannerInventario: `${C}/scanner-inventario.png`,
  scannerResinas: `${C}/scanner-resinas.png`,
  scannerInyeccion: `${C}/scanner-inyeccion.png`,

  // Analytics
  powerbiPlan: '/assets/images/powerbi/powerbi-plan-adherence.png',
  powerbiDrivers: '/assets/images/powerbi/powerbi-performance-drivers.png',

  // Recognition
  gm: '/assets/images/highlights/gm.jpg',
  keepCoding: '/assets/images/highlights/keepcoding.jpg',
  award: '/assets/images/highlights/department-employee-of-the-year.jpg',
};

export const contentByLanguage = {
  en: {
    brandRole: 'Data Engineer · MES · Industrial IoT',
    imageZoomLabel: 'Open image',
    imageCloseLabel: 'Close image preview',
    navigation: [
      { label: 'Impact', href: '#impact' },
      { label: 'MES', href: '#mes' },
      { label: 'ERP', href: '#erp' },
      { label: 'Scanner', href: '#scanner' },
      { label: 'Analytics', href: '#analytics' },
      { label: 'Experience', href: '#experience' },
      { label: 'Contact', href: '#contact' },
    ],
    languageSwitchLabel: 'Select language',
    cvLabel: 'Download CV',
    githubLabel: 'GitHub',
    hero: {
      eyebrow: 'Data Engineer · Manufacturing Systems',
      titleLead: 'I build manufacturing systems that turn',
      titleAccent: 'live data into daily control.',
      description:
        "I'm Juan Roberto García Gómez. I design and ship the software a plant actually runs on — a real-time MES, an ERP, industrial IoT integration and the analytics leadership reviews every morning.",
      primaryAction: 'See the systems',
      secondaryAction: 'Download CV',
      linkedin: 'LinkedIn',
      portraitAlt: 'Professional portrait of Juan Roberto García Gómez',
      focusTitle: 'What I deliver end to end',
      focusItems: [
        'Real-time MES dashboards for the shopfloor and leadership',
        'Production, downtime, quality, tooling and planning modules in daily use',
        'Machine integration, ETL pipelines and Power BI on top of MES + ERP',
      ],
    },
    impact: {
      eyebrow: 'Impact',
      title: 'Outcomes, not just screens',
      description:
        'Every number below comes from systems running in production at a plastic-injection plant in San Luis Potosí.',
      stats: [
        {
          value: '34',
          label: 'machines connected',
          detail: 'EUROMAP63 and Modbus integration across ENGEL, WOOJIN and SUMITOMO injection machines.',
        },
        {
          value: '90%',
          label: 'less manual reporting',
          detail: 'Production now arrives in real time; operators only add downtime and defect context.',
        },
        {
          value: '24/7',
          label: 'plan visibility',
          detail: 'Leadership sees plan vs. actual, stop causes and production running without a plan, live.',
        },
        {
          value: '6',
          label: 'plant areas unified',
          detail: 'Injection, assembly, EPC, tooling, quality and maintenance in one connected MES + ERP platform.',
        },
      ],
    },
    mes: {
      eyebrow: 'Flagship · MES-System',
      title: 'A real-time MES the plant runs on',
      description:
        'One web platform that centralizes injection, assembly, EPC, tooling, quality and live machine data — built with React and Node.js, backed by PostgreSQL.',
      featured: {
        title: 'Live Stop Board & Machine Status',
        subtitle: 'Real-time shopfloor control',
        browserLabel: 'mes.chunil.mx/realtime-data/dashboard',
        image: portfolioAssets.mesRealtime,
        alt: 'Real-time MES dashboard showing live machine status for the whole plant',
        text: 'A single operational screen showing the state of every machine, the live stop board and plan exceptions — so supervisors react the moment production changes during a shift.',
        metrics: [
          { value: '34', label: 'machines live' },
          { value: '3', label: 'shifts/day' },
          { value: 'Socket.IO', label: 'real-time feed' },
          { value: 'React + Node', label: 'full stack' },
        ],
      },
      galleryTitle: 'Inside the MES',
      galleryDescription: 'Core modules used across injection, tooling, quality and EPC every shift.',
      gallery: [
        {
          title: 'Modules Home',
          subtitle: 'Unified entry point',
          browserLabel: 'mes.chunil.mx/home',
          image: portfolioAssets.mesHome,
          alt: 'MES home with access to every module',
          description: 'Role-aware landing page with direct access to every module and live context.',
        },
        {
          title: 'Injection Data',
          subtitle: 'OEE, quality and process detail',
          browserLabel: 'mes.chunil.mx/injection/injection-data',
          image: portfolioAssets.mesInjectionData,
          alt: 'Injection data dashboard with OEE and production records',
          description: 'Availability, performance, quality and OEE with full production records and process variables.',
        },
        {
          title: 'Assembly Data',
          subtitle: 'Line OEE and production records',
          browserLabel: 'mes.chunil.mx/assembly/assembly-data',
          image: portfolioAssets.mesAssemblyData,
          alt: 'Assembly data dashboard with OEE and line records',
          description: 'Assembly-line OEE, OK/NG counts and detailed records by line, customer and part.',
        },
        {
          title: 'EPC Production',
          subtitle: 'Records, PPM and defects',
          browserLabel: 'mes.chunil.mx/epc/epc-data',
          image: portfolioAssets.mesEpcData,
          alt: 'EPC production records dashboard',
          description: 'Millions of pieces tracked with OK/NG breakdown, defect rate and PPM by part and customer.',
        },
        {
          title: 'EPC Cycle-Time Study',
          subtitle: 'Cycle time by part and headcount',
          browserLabel: 'mes.chunil.mx/epc/epc-ct',
          image: portfolioAssets.mesEpcCt,
          alt: 'EPC cycle-time analysis view',
          description: 'Per-part cycle-time analysis with staffing scenarios for planning and export.',
        },
        {
          title: 'PM Runtime Control',
          subtitle: 'Tooling runtime & overdue molds',
          browserLabel: 'mes.chunil.mx/tooling/molds/pm-runtime',
          image: portfolioAssets.mesPmRuntime,
          alt: 'Preventive maintenance runtime dashboard',
          description: 'Live runtime per mold with PM status, due-soon and overdue flags to prevent breakdowns.',
        },
        {
          title: 'Mold Tracking',
          subtitle: 'Tooling traceability',
          browserLabel: 'mes.chunil.mx/tooling/molds/mold-tracking',
          image: portfolioAssets.mesMoldTracking,
          alt: 'Mold tracking system with audit focus',
          description: 'Audit-ready follow-up of every mold: owner, problem, dates and traceability.',
        },
        {
          title: 'Maintenance Orders',
          subtitle: 'Corrective & preventive',
          browserLabel: 'mes.chunil.mx/tooling/maintenance/order',
          image: portfolioAssets.mesMaintenanceOrders,
          alt: 'Tooling maintenance orders dashboard',
          description: 'Create, prioritize and follow tooling maintenance orders with status and waiting days.',
        },
        {
          title: 'Regrind / Grinder Data',
          subtitle: 'Scrap regrind inventory & flow',
          browserLabel: 'mes.chunil.mx/injection/data/regrind',
          image: portfolioAssets.mesRegrind,
          alt: 'Grinder data and regrind inventory dashboard',
          description: 'Regrind inventory, grinder output and extruder consumption traced by part, material and shift.',
        },
        {
          title: 'Quality / Quarantine',
          subtitle: 'Top defects and quarantine control',
          browserLabel: 'mes.chunil.mx/quality-management/quarantine',
          image: portfolioAssets.mesQuarantine,
          alt: 'Quarantine quality dashboard with top defects',
          description: 'Top defects overall plus quarantine inventory control for injection and assembly.',
        },
        {
          title: 'Document Control (QMS)',
          subtitle: '5-level document pyramid',
          browserLabel: 'mes.chunil.mx/quality-management/documents',
          image: portfolioAssets.mesDocumentControl,
          alt: 'Quality document control repository',
          description: 'Central QMS repository with reviewer-approved versioning across thousands of controlled documents.',
        },
      ],
    },
    erp: {
      eyebrow: 'ERP-System',
      title: 'An ERP that connects the back office to the floor',
      description:
        'Production planning, HR incidences, warehouse, finances and purchasing — sharing the same database and identity as the MES, so the plant and the office see one truth.',
      gallery: [
        {
          title: 'ERP Home',
          subtitle: 'Module navigation',
          browserLabel: 'erp.chunil.mx/home',
          image: portfolioAssets.erpHome,
          alt: 'ERP home with module access',
          description: 'Single sign-on entry to planning, HR, warehouse, finances and purchasing.',
        },
        {
          title: 'Production Plan',
          subtitle: 'Manufacturing overview',
          browserLabel: 'erp.chunil.mx/production-plan',
          image: portfolioAssets.erpProductionPlan,
          alt: 'ERP production planning dashboard',
          description: 'Planning and control workspace for injection scheduling and execution follow-up.',
        },
        {
          title: 'HR Incidences',
          subtitle: 'Capture, review & approval',
          browserLabel: 'erp.chunil.mx/rh/incidencias',
          image: portfolioAssets.erpHrIncidencias,
          alt: 'ERP HR incidence management screen',
          description: 'Structured incidence flow with approval states, time-bank logic and time-clock integration — no paper.',
        },
        {
          title: 'Warehouse',
          subtitle: 'Resin & material inventory',
          browserLabel: 'erp.chunil.mx/warehouse',
          image: portfolioAssets.erpWarehouse,
          alt: 'ERP warehouse workspace selector',
          description: 'Inventory across raw resin, subsidiaries, regrind and a shared material master with labeling.',
        },
        {
          title: 'Finances',
          subtitle: 'Accounting workspace',
          browserLabel: 'erp.chunil.mx/finances',
          image: portfolioAssets.erpFinances,
          alt: 'ERP finances module landing',
          description: 'Centralized accounting access with trial balance and financial master data.',
        },
        {
          title: 'Trial Balance',
          subtitle: 'Workbook upload & mapping',
          browserLabel: 'erp.chunil.mx/finances/reports/trial-balance',
          image: portfolioAssets.erpTrialBalance,
          alt: 'ERP trial balance conversion screen',
          description: 'Drop a standard trial-balance workbook and get a mapped, structured breakdown ready to report.',
        },
        {
          title: 'Financial Master Data',
          subtitle: 'Suppliers, accounts & catalogs',
          browserLabel: 'erp.chunil.mx/finances/datos-maestros',
          image: portfolioAssets.erpFinancesMaster,
          alt: 'ERP financial master data administration',
          description: 'Catalog administration for suppliers, concepts, customers and categories with change audit.',
        },
        {
          title: 'Purchasing',
          subtitle: 'Purchase-order requests',
          browserLabel: 'erp.chunil.mx/compras',
          image: portfolioAssets.erpPurchasing,
          alt: 'ERP purchasing order request flow',
          description: 'Guided purchase-order requests with supplier, tax data, approval and history.',
        },
      ],
    },
    scanner: {
      eyebrow: 'Mobile · Inventory Scanner',
      title: 'A barcode scanner app for the warehouse',
      description:
        'A React Native (Expo) companion app that puts inventory in the operator’s hand — scanning resin, subsidiary and injection materials straight into the same ERP database.',
      footnote: 'Built with React Native + Expo · shares the ERP identity and database.',
      gallery: [
        {
          title: 'Inventory menu',
          subtitle: 'Materials by category',
          image: portfolioAssets.scannerInventario,
          alt: 'Scanner app inventory menu',
          description: 'Raw resin, subsidiaries and injection materials, each with stock, lots, movements and events.',
        },
        {
          title: 'Raw material',
          subtitle: 'Resin stock & handling units',
          image: portfolioAssets.scannerResinas,
          alt: 'Scanner app raw material inventory',
          description: 'Counts, receipts from inbound and movements for base resin materials.',
        },
        {
          title: 'Injection inventory',
          subtitle: 'Materials tied to injection',
          image: portfolioAssets.scannerInyeccion,
          alt: 'Scanner app injection inventory',
          description: 'Stock balances, lots and movements linked to the injection process on the floor.',
        },
      ],
    },
    analytics: {
      eyebrow: 'Analytics',
      title: 'Power BI on top of the operation',
      description:
        'When leadership needs the weekly view, the same manufacturing data flows into clean, review-ready Power BI dashboards.',
      gallery: [
        {
          title: 'Plan Adherence Review',
          subtitle: 'Planned vs. achieved, weekly',
          image: portfolioAssets.powerbiPlan,
          alt: 'Power BI plan adherence dashboard',
          description: 'Planned, achieved, not-produced and overproduction with adherence and quality at a glance.',
        },
        {
          title: 'Performance Drivers',
          subtitle: 'Where the gaps come from',
          image: portfolioAssets.powerbiDrivers,
          alt: 'Power BI performance drivers dashboard',
          description: 'Top not-produced and overproduced pieces by part and customer to target the real drivers.',
        },
      ],
    },
    support: {
      eyebrow: 'How I work',
      title: 'Where I create the most value',
      description:
        'I create the most value where operations, industrial data and software delivery have to move together.',
      items: [
        {
          title: 'MES & Industrial IoT',
          text: 'I connect machines, plant logic and user workflows into systems operations can use every shift.',
        },
        {
          title: 'Operational dashboards',
          text: 'I build real-time screens that are readable, useful and aligned with daily plant decisions.',
        },
        {
          title: 'Data engineering & ETL',
          text: 'I design databases, pipelines and business rules that make manufacturing data reliable.',
        },
        {
          title: 'Power BI & automation',
          text: 'I turn raw data into recurring reports and management dashboards that are ready to review.',
        },
      ],
    },
    experience: {
      eyebrow: 'Experience',
      title: 'Built in real operation',
      description: 'Manufacturing execution, data engineering and analytics tied to business outcomes.',
      items: [
        {
          company: 'Chunil Mexico',
          role: 'Data Engineer · MES & Manufacturing Analytics',
          period: 'Oct 2024 — Present',
          summary:
            'Designed and shipped a production MES and ERP for a plastic-injection plant: industrial integration, backend services, analytics and React apps for shopfloor teams.',
          bullets: [
            'Centralized injection, assembly, EPC, tooling and plant operations in one web platform.',
            'Integrated 34 machines into real-time dashboards, historical analysis and downtime logic.',
            'Recognized as Department Employee of the Year.',
          ],
        },
        {
          company: 'Ramirez Valle & Asociados · General Motors SLP',
          role: 'Claims, Loss & Recovery Coordinator',
          period: 'Oct 2023 — 2024',
          summary:
            'Operational analytics focused on financial recovery, evidence management and executive visibility.',
          bullets: [
            'Led data-driven logistics claims analysis and financial recovery.',
            'Built Power BI dashboards that cut analysis time by 40%.',
            'Structured evidence and tracking workflows for 100+ cases.',
          ],
        },
      ],
    },
    recognition: {
      eyebrow: 'Recognition & training',
      title: 'The background behind the work',
      publicationLabel: 'View on LinkedIn',
      items: [
        {
          title: 'Department Employee of the Year',
          kicker: 'Recognition',
          text: 'Recognized at Chunil Mexico for discipline, execution and measurable contribution.',
          image: portfolioAssets.award,
          alt: 'Department Employee of the Year recognition',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'KeepCoding',
          kicker: 'Advanced training',
          text: 'Big Data, AI, Machine Learning and full-stack training applied to real delivery.',
          image: portfolioAssets.keepCoding,
          alt: 'KeepCoding certification',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'General Motors SLP',
          kicker: 'Business exposure',
          text: 'Operational analytics, claims recovery and executive visibility in an industrial environment.',
          image: portfolioAssets.gm,
          alt: 'General Motors San Luis Potosí team',
          publicationUrl: contactLinks.linkedin,
        },
      ],
    },
    education: {
      eyebrow: 'Education',
      title: 'Training and core stack',
      description: 'Academic and technical background applied to manufacturing and analytics.',
      educationTitle: 'Education',
      stackTitle: 'Core stack',
      languagesTitle: 'Languages',
      items: [
        'Full Stack Web Development Bootcamp, KeepCoding · Nov 2025 — Present',
        'Business Analytics, Tecnológico de Monterrey · Jan 2025 — Apr 2025',
        'Big Data, AI & Machine Learning Bootcamp, KeepCoding · Jun 2023 — Jun 2024',
        'Python for Data Science, IICO · May 2022 — Aug 2022',
        'BA in Economics, UASLP · Aug 2018 — Jul 2023',
        'Industrial & Logistics Engineering, UNID · Aug 2014 — Jul 2017',
      ],
      stack: [
        'PostgreSQL', 'SQL', 'Node.js', 'React', 'Vite', 'REST APIs',
        'Socket.IO', 'ETL', 'Power BI', 'OEE', 'Modbus', 'EUROMAP63',
      ],
      languages: ['Spanish — Native', 'English — Professional working proficiency'],
    },
    closing: {
      eyebrow: 'Available for collaboration',
      title: 'If your operation needs to run on better systems, that is exactly where I fit.',
      description:
        'Independent or in-house — I can lead MES, Industrial IoT, dashboards, Power BI, reporting automation and connected manufacturing applications.',
      primary: 'Email me',
      quaternary: 'LinkedIn',
    },
    footer: {
      role: 'Data Engineer · Industrial IoT · Manufacturing Systems',
      builtWith: 'Built with React + Vite + Framer Motion',
    },
  },

  es: {
    brandRole: 'Data Engineer · MES · Industrial IoT',
    imageZoomLabel: 'Abrir imagen',
    imageCloseLabel: 'Cerrar vista de imagen',
    navigation: [
      { label: 'Impacto', href: '#impact' },
      { label: 'MES', href: '#mes' },
      { label: 'ERP', href: '#erp' },
      { label: 'Scanner', href: '#scanner' },
      { label: 'Analítica', href: '#analytics' },
      { label: 'Experiencia', href: '#experience' },
      { label: 'Contacto', href: '#contact' },
    ],
    languageSwitchLabel: 'Seleccionar idioma',
    cvLabel: 'Descargar CV',
    githubLabel: 'GitHub',
    hero: {
      eyebrow: 'Data Engineer · Sistemas de manufactura',
      titleLead: 'Construyo sistemas de manufactura que vuelven los',
      titleAccent: 'datos en vivo en control diario.',
      description:
        'Soy Juan Roberto García Gómez. Diseño y entrego el software con el que opera una planta: un MES en tiempo real, un ERP, integración de IoT industrial y la analítica que la dirección revisa cada mañana.',
      primaryAction: 'Ver los sistemas',
      secondaryAction: 'Descargar CV',
      linkedin: 'LinkedIn',
      portraitAlt: 'Foto profesional de Juan Roberto García Gómez',
      focusTitle: 'Lo que entrego de inicio a fin',
      focusItems: [
        'Dashboards MES en tiempo real para shopfloor y dirección',
        'Módulos de producción, paros, calidad, tooling y planeación en uso diario',
        'Integración de máquinas, pipelines ETL y Power BI sobre MES + ERP',
      ],
    },
    impact: {
      eyebrow: 'Impacto',
      title: 'Resultados, no solo pantallas',
      description:
        'Cada número proviene de sistemas en producción en una planta de inyección de plástico en San Luis Potosí.',
      stats: [
        {
          value: '34',
          label: 'máquinas conectadas',
          detail: 'Integración EUROMAP63 y Modbus en máquinas de inyección ENGEL, WOOJIN y SUMITOMO.',
        },
        {
          value: '90%',
          label: 'menos captura manual',
          detail: 'La producción llega en tiempo real; el equipo solo agrega contexto de paros y defectos.',
        },
        {
          value: '24/7',
          label: 'visibilidad del plan',
          detail: 'La dirección ve plan vs. real, causas de paro y producción corriendo sin plan, en vivo.',
        },
        {
          value: '6',
          label: 'áreas de planta unificadas',
          detail: 'Inyección, ensamble, EPC, tooling, calidad y mantenimiento en una sola plataforma MES + ERP.',
        },
      ],
    },
    mes: {
      eyebrow: 'Sistema principal · MES-System',
      title: 'Un MES en tiempo real con el que opera la planta',
      description:
        'Una plataforma web que centraliza inyección, ensamble, EPC, tooling, calidad y datos de máquina en vivo — hecha con React y Node.js, sobre PostgreSQL.',
      featured: {
        title: 'Live Stop Board y estado de máquinas',
        subtitle: 'Control de shopfloor en tiempo real',
        browserLabel: 'mes.chunil.mx/realtime-data/dashboard',
        image: portfolioAssets.mesRealtime,
        alt: 'Dashboard MES en tiempo real con el estado de todas las máquinas de la planta',
        text: 'Una sola pantalla operativa con el estado de cada máquina, el stop board en vivo y las excepciones del plan — para reaccionar en el momento en que cambia la producción durante el turno.',
        metrics: [
          { value: '34', label: 'máquinas en vivo' },
          { value: '3', label: 'turnos/día' },
          { value: 'Socket.IO', label: 'feed en tiempo real' },
          { value: 'React + Node', label: 'full stack' },
        ],
      },
      galleryTitle: 'Dentro del MES',
      galleryDescription: 'Módulos centrales usados en inyección, tooling, calidad y EPC cada turno.',
      gallery: [
        {
          title: 'Home de módulos',
          subtitle: 'Punto de entrada unificado',
          browserLabel: 'mes.chunil.mx/home',
          image: portfolioAssets.mesHome,
          alt: 'Home del MES con acceso a cada módulo',
          description: 'Pantalla principal por rol con acceso directo a cada módulo y contexto en vivo.',
        },
        {
          title: 'Injection Data',
          subtitle: 'OEE, calidad y detalle de proceso',
          browserLabel: 'mes.chunil.mx/injection/injection-data',
          image: portfolioAssets.mesInjectionData,
          alt: 'Dashboard de injection data con OEE y registros de producción',
          description: 'Disponibilidad, desempeño, calidad y OEE con registros completos y variables de proceso.',
        },
        {
          title: 'Assembly Data',
          subtitle: 'OEE de línea y registros',
          browserLabel: 'mes.chunil.mx/assembly/assembly-data',
          image: portfolioAssets.mesAssemblyData,
          alt: 'Dashboard de assembly data con OEE y registros de línea',
          description: 'OEE de línea de ensamble, conteos OK/NG y registros detallados por línea, cliente y parte.',
        },
        {
          title: 'Producción EPC',
          subtitle: 'Registros, PPM y defectos',
          browserLabel: 'mes.chunil.mx/epc/epc-data',
          image: portfolioAssets.mesEpcData,
          alt: 'Dashboard de registros de producción EPC',
          description: 'Millones de piezas con desglose OK/NG, tasa de defecto y PPM por parte y cliente.',
        },
        {
          title: 'Estudio de tiempo ciclo EPC',
          subtitle: 'Ciclo por parte y personal',
          browserLabel: 'mes.chunil.mx/epc/epc-ct',
          image: portfolioAssets.mesEpcCt,
          alt: 'Vista de análisis de tiempo ciclo EPC',
          description: 'Análisis de tiempo ciclo por parte con escenarios de personal para planeación y exportación.',
        },
        {
          title: 'PM Runtime Control',
          subtitle: 'Runtime de tooling y moldes vencidos',
          browserLabel: 'mes.chunil.mx/tooling/molds/pm-runtime',
          image: portfolioAssets.mesPmRuntime,
          alt: 'Dashboard de runtime de mantenimiento preventivo',
          description: 'Runtime por molde en vivo con estado de PM y alertas de próximo y vencido para evitar fallas.',
        },
        {
          title: 'Mold Tracking',
          subtitle: 'Trazabilidad de tooling',
          browserLabel: 'mes.chunil.mx/tooling/molds/mold-tracking',
          image: portfolioAssets.mesMoldTracking,
          alt: 'Sistema de mold tracking con enfoque de auditoría',
          description: 'Seguimiento listo para auditoría de cada molde: responsable, problema, fechas y trazabilidad.',
        },
        {
          title: 'Órdenes de mantenimiento',
          subtitle: 'Correctivo y preventivo',
          browserLabel: 'mes.chunil.mx/tooling/maintenance/order',
          image: portfolioAssets.mesMaintenanceOrders,
          alt: 'Dashboard de órdenes de mantenimiento de tooling',
          description: 'Crea, prioriza y da seguimiento a órdenes de tooling con estado y días en espera.',
        },
        {
          title: 'Regrind / Grinder Data',
          subtitle: 'Inventario y flujo de regrind',
          browserLabel: 'mes.chunil.mx/injection/data/regrind',
          image: portfolioAssets.mesRegrind,
          alt: 'Dashboard de grinder data e inventario de regrind',
          description: 'Inventario de regrind, salida de molino y consumo de extrusor por parte, material y turno.',
        },
        {
          title: 'Calidad / Cuarentena',
          subtitle: 'Top de defectos y control de cuarentena',
          browserLabel: 'mes.chunil.mx/quality-management/quarantine',
          image: portfolioAssets.mesQuarantine,
          alt: 'Dashboard de calidad y cuarentena con top de defectos',
          description: 'Top de defectos general y control de inventario en cuarentena para inyección y ensamble.',
        },
        {
          title: 'Control de documentos (QMS)',
          subtitle: 'Pirámide documental de 5 niveles',
          browserLabel: 'mes.chunil.mx/quality-management/documents',
          image: portfolioAssets.mesDocumentControl,
          alt: 'Repositorio de control de documentos de calidad',
          description: 'Repositorio QMS central con versionado aprobado por revisor sobre miles de documentos controlados.',
        },
      ],
    },
    erp: {
      eyebrow: 'ERP-System',
      title: 'Un ERP que conecta el back office con el piso',
      description:
        'Planeación de producción, incidencias de RH, almacén, finanzas y compras — compartiendo la misma base de datos e identidad que el MES, para que planta y oficina vean una sola verdad.',
      gallery: [
        {
          title: 'Home del ERP',
          subtitle: 'Navegación de módulos',
          browserLabel: 'erp.chunil.mx/home',
          image: portfolioAssets.erpHome,
          alt: 'Home del ERP con acceso a módulos',
          description: 'Entrada con sesión única a planeación, RH, almacén, finanzas y compras.',
        },
        {
          title: 'Plan de producción',
          subtitle: 'Visión de manufactura',
          browserLabel: 'erp.chunil.mx/production-plan',
          image: portfolioAssets.erpProductionPlan,
          alt: 'Dashboard de planeación de producción del ERP',
          description: 'Espacio de planeación y control para la programación de inyección y su seguimiento.',
        },
        {
          title: 'Incidencias RH',
          subtitle: 'Captura, revisión y aprobación',
          browserLabel: 'erp.chunil.mx/rh/incidencias',
          image: portfolioAssets.erpHrIncidencias,
          alt: 'Pantalla de gestión de incidencias de RH del ERP',
          description: 'Flujo de incidencias con estados de aprobación, banco de tiempo y conexión al reloj checador — sin papel.',
        },
        {
          title: 'Almacén',
          subtitle: 'Inventario de resina y material',
          browserLabel: 'erp.chunil.mx/warehouse',
          image: portfolioAssets.erpWarehouse,
          alt: 'Selector de áreas de trabajo de almacén del ERP',
          description: 'Inventario de resina, subsidiarios, regrind y un maestro de materiales compartido con etiquetado.',
        },
        {
          title: 'Finanzas',
          subtitle: 'Espacio contable',
          browserLabel: 'erp.chunil.mx/finances',
          image: portfolioAssets.erpFinances,
          alt: 'Landing del módulo de finanzas del ERP',
          description: 'Acceso contable centralizado con balanza de comprobación y datos maestros financieros.',
        },
        {
          title: 'Balanza de comprobación',
          subtitle: 'Carga y mapeo de workbook',
          browserLabel: 'erp.chunil.mx/finances/reports/trial-balance',
          image: portfolioAssets.erpTrialBalance,
          alt: 'Pantalla de conversión de balanza de comprobación del ERP',
          description: 'Sube una balanza estándar y obtén un desglose mapeado y estructurado listo para reportar.',
        },
        {
          title: 'Datos maestros financieros',
          subtitle: 'Proveedores, cuentas y catálogos',
          browserLabel: 'erp.chunil.mx/finances/datos-maestros',
          image: portfolioAssets.erpFinancesMaster,
          alt: 'Administración de datos maestros financieros del ERP',
          description: 'Administración de catálogos de proveedores, conceptos, clientes y categorías con auditoría de cambios.',
        },
        {
          title: 'Compras',
          subtitle: 'Solicitudes de orden de compra',
          browserLabel: 'erp.chunil.mx/compras',
          image: portfolioAssets.erpPurchasing,
          alt: 'Flujo de solicitud de orden de compra del ERP',
          description: 'Solicitudes guiadas de orden de compra con proveedor, datos fiscales, aprobación e historial.',
        },
      ],
    },
    scanner: {
      eyebrow: 'Móvil · Inventory Scanner',
      title: 'Una app de escaneo para el almacén',
      description:
        'Una app complementaria en React Native (Expo) que pone el inventario en la mano del operador — escaneando resina, subsidiarios y material de inyección directo a la misma base de datos del ERP.',
      footnote: 'Hecha con React Native + Expo · comparte identidad y base de datos con el ERP.',
      gallery: [
        {
          title: 'Menú de inventario',
          subtitle: 'Materiales por categoría',
          image: portfolioAssets.scannerInventario,
          alt: 'Menú de inventario de la app de escaneo',
          description: 'Materia prima, subsidiarios e inyección, cada uno con stock, lotes, movimientos y eventos.',
        },
        {
          title: 'Materia prima',
          subtitle: 'Stock y handling units de resina',
          image: portfolioAssets.scannerResinas,
          alt: 'Inventario de materia prima de la app',
          description: 'Conteos, entradas desde recibo y movimientos para materiales base de resina.',
        },
        {
          title: 'Inventario de inyección',
          subtitle: 'Materiales ligados a inyección',
          image: portfolioAssets.scannerInyeccion,
          alt: 'Inventario de inyección de la app',
          description: 'Stock balances, lotes y movimientos ligados al proceso de inyección en planta.',
        },
      ],
    },
    analytics: {
      eyebrow: 'Analítica',
      title: 'Power BI sobre la operación',
      description:
        'Cuando la dirección necesita la vista semanal, los mismos datos de manufactura fluyen a dashboards Power BI limpios y listos para revisión.',
      gallery: [
        {
          title: 'Revisión de adherencia',
          subtitle: 'Plan vs. logrado, semanal',
          image: portfolioAssets.powerbiPlan,
          alt: 'Dashboard Power BI de adherencia al plan',
          description: 'Plan, logrado, no producido y sobreproducción con adherencia y calidad de un vistazo.',
        },
        {
          title: 'Drivers de desempeño',
          subtitle: 'De dónde vienen las brechas',
          image: portfolioAssets.powerbiDrivers,
          alt: 'Dashboard Power BI de drivers de desempeño',
          description: 'Top de piezas no producidas y sobreproducidas por parte y cliente para atacar los drivers reales.',
        },
      ],
    },
    support: {
      eyebrow: 'Cómo trabajo',
      title: 'Dónde genero más valor',
      description:
        'Genero más valor donde operación, datos industriales y entrega de software deben avanzar juntos.',
      items: [
        {
          title: 'MES e Industrial IoT',
          text: 'Conecto máquinas, lógica de planta y flujos de usuario en sistemas que operación usa cada turno.',
        },
        {
          title: 'Dashboards operativos',
          text: 'Construyo vistas en tiempo real claras, útiles y alineadas con decisiones de planta.',
        },
        {
          title: 'Data engineering y ETL',
          text: 'Diseño bases de datos, pipelines y reglas de negocio que vuelven confiables los datos de manufactura.',
        },
        {
          title: 'Power BI y automatización',
          text: 'Convierto datos crudos en reportes recurrentes y dashboards gerenciales listos para revisión.',
        },
      ],
    },
    experience: {
      eyebrow: 'Experiencia',
      title: 'Construido en operación real',
      description: 'Manufactura, data engineering y analítica orientada a resultados de negocio.',
      items: [
        {
          company: 'Chunil Mexico',
          role: 'Data Engineer · MES & Manufacturing Analytics',
          period: 'Oct 2024 — Actualidad',
          summary:
            'Diseñé y entregué un MES y un ERP productivos para una planta de inyección: integración industrial, backend, analítica y apps React para shopfloor.',
          bullets: [
            'Centralicé inyección, ensamble, EPC, tooling y operación de planta en una sola plataforma web.',
            'Integré 34 máquinas a dashboards en tiempo real, análisis histórico y lógica de downtime.',
            'Reconocido como Mejor Empleado del Departamento del Año.',
          ],
        },
        {
          company: 'Ramirez Valle & Asociados · General Motors SLP',
          role: 'Claims, Loss & Recovery Coordinator',
          period: 'Oct 2023 — 2024',
          summary:
            'Analítica operativa enfocada en recuperación financiera, gestión de evidencia y visibilidad ejecutiva.',
          bullets: [
            'Lideré análisis data-driven de claims logísticos y recuperación financiera.',
            'Construí dashboards Power BI que redujeron 40% el tiempo de análisis.',
            'Estructuré flujos de evidencia y seguimiento para más de 100 casos.',
          ],
        },
      ],
    },
    recognition: {
      eyebrow: 'Reconocimiento y formación',
      title: 'La trayectoria detrás del trabajo',
      publicationLabel: 'Ver en LinkedIn',
      items: [
        {
          title: 'Mejor empleado del departamento del año',
          kicker: 'Reconocimiento',
          text: 'Reconocimiento en Chunil Mexico por disciplina, ejecución e impacto medible.',
          image: portfolioAssets.award,
          alt: 'Reconocimiento al mejor empleado del departamento del año',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'KeepCoding',
          kicker: 'Formación avanzada',
          text: 'Bootcamp aplicado a proyectos reales de datos, IA y desarrollo full-stack.',
          image: portfolioAssets.keepCoding,
          alt: 'Certificación de KeepCoding',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'General Motors SLP',
          kicker: 'Experiencia de negocio',
          text: 'Analítica operativa, recuperación de claims y visibilidad ejecutiva en entorno industrial.',
          image: portfolioAssets.gm,
          alt: 'Equipo de General Motors San Luis Potosí',
          publicationUrl: contactLinks.linkedin,
        },
      ],
    },
    education: {
      eyebrow: 'Educación',
      title: 'Formación y stack principal',
      description: 'Base académica y técnica aplicada a manufactura y analítica.',
      educationTitle: 'Formación',
      stackTitle: 'Stack principal',
      languagesTitle: 'Idiomas',
      items: [
        'Bootcamp Full Stack Web Development, KeepCoding · Nov 2025 — Actualidad',
        'Business Analytics, Tecnológico de Monterrey · Ene 2025 — Abr 2025',
        'Bootcamp Big Data, AI & Machine Learning, KeepCoding · Jun 2023 — Jun 2024',
        'Python for Data Science, IICO · May 2022 — Ago 2022',
        'Licenciatura en Economía, UASLP · Ago 2018 — Jul 2023',
        'Ingeniería Industrial y Logística, UNID · Ago 2014 — Jul 2017',
      ],
      stack: [
        'PostgreSQL', 'SQL', 'Node.js', 'React', 'Vite', 'REST APIs',
        'Socket.IO', 'ETL', 'Power BI', 'OEE', 'Modbus', 'EUROMAP63',
      ],
      languages: ['Español — Nativo', 'Inglés — Nivel profesional de trabajo'],
    },
    closing: {
      eyebrow: 'Disponible para colaborar',
      title: 'Si tu operación necesita correr sobre mejores sistemas, ahí es exactamente donde encajo.',
      description:
        'Independiente o en empresa — puedo liderar MES, Industrial IoT, dashboards, Power BI, automatización de reportes y aplicaciones conectadas de manufactura.',
      primary: 'Escríbeme',
      quaternary: 'LinkedIn',
    },
    footer: {
      role: 'Data Engineer · Industrial IoT · Sistemas de manufactura',
      builtWith: 'Hecho con React + Vite + Framer Motion',
    },
  },
};
