export const githubLinks = {
  organisation: 'https://github.com/Robertogag',
  mes: 'https://github.com/Chunil-Mexico/MES-System',
  erp: 'https://github.com/Chunil-Mexico/ERP-System',
};

export const contactLinks = {
  email: 'mailto:roberto.gag117@gmail.com',
  emailLabel: 'roberto.gag117@gmail.com',
  linkedin: 'https://www.linkedin.com/in/juan-roberto-garc%C3%ADa-g%C3%B3mez1/',
};

export const portfolioAssets = {
  cv: '/assets/docs/juan-roberto-garcia-cv-2026.pdf',
  profile: '/assets/images/roberto-profile-cv2.png',
  mesHome: '/assets/images/mes-home-dashboard.png',
  mesLiveStopBoard: '/assets/images/mes-live-stop-board.png',
  mesLineStopHistory: '/assets/images/mes-line-stop-history.png',
  mesProductionPlan: '/assets/images/weekly-plan-progress-realtime.png',
  realtimeDashboard: '/assets/images/mes-live-stop-board.png',
  injectionData: '/assets/images/injection-data.png',
  telemetry: '/assets/images/telemetry.png',
  toolingPm: '/assets/images/tooling-pm.png',
  moldTracking: '/assets/images/mold-tracking.png',
  moldMaintenanceOrders: '/assets/images/mold-maintenance-orders.png',
  powerbiPlan: '/assets/images/powerbi/powerbi-plan-adherence.png',
  powerbiDrivers: '/assets/images/powerbi/powerbi-performance-drivers.png',
  gm: '/assets/images/highlights/gm.jpg',
  keepCoding: '/assets/images/highlights/keepcoding.jpg',
  award: '/assets/images/highlights/department-employee-of-the-year.jpg',
  erpIncidencias: '/assets/images/hr-incidencias.png',
  erpProductionPlan: '/assets/images/erp/erp-production-plan.png',
};

export const contentByLanguage = {
  en: {
    brandRole: 'Data Engineer | Industrial IoT | MES',
    imageZoomLabel: 'Open image',
    imageCloseLabel: 'Close image preview',
    navigation: [
      { label: 'Featured', href: '#featured' },
      { label: 'Systems', href: '#systems' },
      { label: 'Experience', href: '#experience' },
      { label: 'Education', href: '#education' },
      { label: 'Contact', href: '#contact' },
    ],
    languageSwitchLabel: 'Select language',
    cvLabel: 'Download CV',
    githubLabel: 'GitHub',
    hero: {
      badge: 'Digital portfolio for MES, Industrial IoT and analytics',
      titleLead: 'I design manufacturing systems that',
      titleAccent: 'turn live data into operational control.',
      description:
        'I am Juan Roberto Garc\u00eda G\u00f3mez, a Data Engineer building MES, Industrial IoT and operational analytics for manufacturing.',
      primaryAction: 'See flagship MES dashboard',
      secondaryAction: 'Open CV PDF',
      linkedin: 'LinkedIn',
      portraitAlt: 'Professional portrait of Juan Roberto Garc\u00eda G\u00f3mez',
      focusTitle: 'What I bring to a company',
      focusItems: [
        'Realtime MES dashboards for shopfloor and leadership',
        'Production, downtime, quality and planning modules built for daily use',
        'Power BI, ETL and connected systems across MES and ERP',
      ],
    },
    stats: [
      {
        value: '90%',
        label: 'less manual reporting',
        detail: 'production now arrives in real time, while operators only add downtime and defect context',
      },
      {
        value: '0 paper',
        label: 'digital HR control',
        detail: 'attendance and time-bank tracking now run through time-clock integration with no paper forms',
      },
      {
        value: '24/7',
        label: 'production plan visibility',
        detail: 'leadership sees plan vs actual, stop causes and production running without plan',
      },
      {
        value: '34',
        label: 'injection machines connected',
        detail: 'Euromap63 and Modbus integration across ENGEL, WOOJIN and SUMITOMO machines',
      },
    ],
    showcase: {
      eyebrow: 'Professional context',
      title: 'Recognition, training and industrial background',
      description: 'A concise visual reference for the experiences behind my work.',
      publicationLabel: 'View on LinkedIn',
      items: [
        {
          title: 'Department Employee of the Year',
          kicker: 'Recognition',
          text: 'Recognition at Chunil Mexico for discipline, execution and measurable contribution.',
          image: portfolioAssets.award,
          alt: 'Department Employee of the Year recognition',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'KeepCoding',
          kicker: 'Advanced training',
          text: 'Big Data, AI, Machine Learning and full-stack training applied to real delivery.',
          image: portfolioAssets.keepCoding,
          alt: 'KeepCoding certification',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'General Motors SLP',
          kicker: 'Business exposure',
          text: 'Operational analytics, claims recovery and executive visibility in an industrial environment.',
          image: portfolioAssets.gm,
          alt: 'General Motors San Luis Potosi team image',
          publicationUrl: contactLinks.linkedin,
        },
      ],
    },
    featured: {
      eyebrow: 'Flagship system',
      title: 'Realtime MES Dashboard',
      description:
        'A live operating view that gives the plant immediate visibility into machine status, stop conditions and execution signals.',
      imageAlt: 'Realtime MES live stop board dashboard',
      points: [
        'Shows machine state, stop board and plan exceptions in one operational screen',
        'Helps supervisors react faster when production changes during the shift',
        'Designed for clear visual control on the shopfloor',
      ],
      metrics: [
        { value: '34', label: 'connected machines' },
        { value: 'Live', label: 'stop board control' },
        { value: 'Shift', label: 'operational follow-up' },
        { value: 'React + Node', label: 'full-stack delivery' },
      ],
    },
    systems: {
      eyebrow: 'Selected work',
      title: 'Systems built for operation',
      description:
        'MES modules, analytics, and business tools used in day-to-day plant operation.',
      previousLabel: 'Previous',
      nextLabel: 'Next',
      modulesTitle: 'MES modules',
      modulesDescription: 'Core operational screens built for daily plant execution.',
      modules: [
        {
          title: 'MES Home',
          subtitle: 'Main navigation and realtime access',
          description: 'The main entry point of the MES with direct access to modules and live context.',
          image: portfolioAssets.mesHome,
          alt: 'MES home dashboard',
        },
        {
          title: 'Realtime MES Dashboard',
          subtitle: 'Live stop board and machine status',
          description: 'A visual control screen built to monitor status, exceptions and shift behavior in real time.',
          image: portfolioAssets.mesLiveStopBoard,
          alt: 'Realtime MES dashboard',
        },
        {
          title: 'Weekly Plan Adherence',
          subtitle: 'Injection target versus real execution',
          description: 'A weekly view to compare planned output against actual production with immediate clarity.',
          image: portfolioAssets.mesProductionPlan,
          alt: 'Weekly plan adherence dashboard',
        },
        {
          title: 'Injection Data',
          subtitle: 'Production detail and process visibility',
          description: 'A focused screen for process variables, production records and injection context.',
          image: portfolioAssets.injectionData,
          alt: 'Injection data dashboard',
        },
        {
          title: 'Telemetry Report',
          subtitle: 'Process variables and cycle analysis',
          description: 'A technical view for cycle time, pressure, fill time and process behavior by run.',
          image: portfolioAssets.telemetry,
          alt: 'Injection telemetry report',
        },
        {
          title: 'Line Stop History',
          subtitle: 'Downtime review and justification',
          description: 'A workflow to review stop events, inspect downtime detail and support justification.',
          image: portfolioAssets.mesLineStopHistory,
          alt: 'Line stop history workflow',
        },
        {
          title: 'Preventive Maintenance Status',
          subtitle: 'Tooling runtime and PM visibility',
          description: 'A tooling dashboard that highlights runtime, overdue molds and preventive maintenance status.',
          image: portfolioAssets.toolingPm,
          alt: 'Tooling preventive maintenance dashboard',
        },
        {
          title: 'Mold Tracking',
          subtitle: 'Tooling follow-up',
          description: 'A tooling view to track ownership, progress, dates and problem status.',
          image: portfolioAssets.moldTracking,
          alt: 'Mold tracking system',
        },
        {
          title: 'Maintenance Orders',
          subtitle: 'Corrective and preventive execution',
          description: 'An order management view for tooling requests, maintenance type and problem detail.',
          image: portfolioAssets.moldMaintenanceOrders,
          alt: 'Tooling maintenance orders dashboard',
        },
      ],
      analyticsTitle: 'Analytics and business review',
      analyticsDescription: 'Executive views that complement realtime operations.',
      analytics: [
        {
          title: 'Power BI Operations Review',
          subtitle: 'Leadership-ready visibility',
          description: 'A clean analytical layer for production reviews, execution control and management follow-up.',
          image: portfolioAssets.powerbiPlan,
          alt: 'Power BI operations review dashboard',
        },
        {
          title: 'Power BI Performance Drivers',
          subtitle: 'Business performance insight',
          description: 'A complementary view focused on trends, performance signals and operational drivers.',
          image: portfolioAssets.powerbiDrivers,
          alt: 'Power BI performance drivers dashboard',
        },
      ],
      enterpriseTitle: 'ERP-System',
      enterpriseDescription: 'Real ERP workflows for incidences and injection planning.',
      enterprise: [
        {
          title: 'ERP Incidences',
          subtitle: 'HR workflow for incident capture',
          description: 'A structured flow to create, review and manage employee incidences inside the ERP.',
          image: portfolioAssets.erpIncidencias,
          alt: 'ERP incident management screen',
        },
        {
          title: 'Injection Production Plan',
          subtitle: 'Planning view for production control',
          description: 'A planning screen focused on injection scheduling and production execution follow-up.',
          image: portfolioAssets.erpProductionPlan,
          alt: 'ERP production planning dashboard',
        },
      ],
    },
    support: {
      eyebrow: 'How I can help',
      title: 'Where I create the strongest value',
      description:
        'I create the most value where operations, industrial data and software delivery need to move together.',
      items: [
        {
          title: 'MES and Industrial IoT',
          text: 'I connect machines, plant logic and user workflows into systems that operations can use every shift.',
        },
        {
          title: 'Operational dashboards',
          text: 'I build realtime screens that are readable, useful and aligned with daily plant decisions.',
        },
        {
          title: 'Data engineering and ETL',
          text: 'I design databases, pipelines and business rules to make manufacturing data reliable.',
        },
        {
          title: 'Power BI and automation',
          text: 'I turn raw data into recurring reports, management dashboards and review-ready analytics.',
        },
      ],
    },
    experience: {
      eyebrow: 'Experience',
      title: 'Results built in real operation',
      description: 'Manufacturing execution, data engineering and analytics tied to business outcomes.',
      items: [
        {
          company: 'Chunil Mexico',
          role: 'Data Engineer | MES & Manufacturing Analytics',
          period: 'Oct 2024 - Present',
          summary:
            'Built a production MES platform for manufacturing with industrial integration, backend services, analytics and React applications for shopfloor teams.',
          bullets: [
            'Centralized injection, assembly, EPC, tooling and plant operations inside one web platform.',
            'Integrated 34 machines into realtime dashboards, historical analysis and downtime logic.',
            'Recognized as Department Employee of the Year in my current company.',
          ],
        },
        {
          company: 'Ramirez Valle & Asociados | General Motors SLP',
          role: 'Claims, Loss & Recovery Coordinator',
          period: 'Oct 2023 - 2024',
          summary:
            'Operational analytics role focused on financial recovery, evidence management and executive visibility.',
          bullets: [
            'Recovered MX$15.2M through data-driven logistics claims analysis.',
            'Built Power BI dashboards that reduced analysis time by 40 percent.',
            'Structured evidence and tracking workflows for more than 100 cases.',
          ],
        },
      ],
    },
    education: {
      eyebrow: 'Education',
      title: 'Training and core stack',
      description: 'Academic and technical background applied to manufacturing and analytics.',
      educationTitle: 'Education',
      stackTitle: 'Core stack',
      languagesTitle: 'Languages',
      items: [
        'Full Stack Web Development Bootcamp, KeepCoding | Nov 2025 - Present',
        'Business Analytics, Tecnologico de Monterrey | Jan 2025 - Apr 2025',
        'Big Data, AI and Machine Learning Bootcamp, KeepCoding | Jun 2023 - Jun 2024',
        'Python for Data Science, IICO | May 2022 - Aug 2022',
        'BA in Economics, UASLP | Aug 2018 - Jul 2023',
        'Industrial and Logistics Engineering, UNID | Aug 2014 - Jul 2017',
      ],
      stack: [
        'PostgreSQL',
        'SQL',
        'Node.js',
        'React',
        'Vite',
        'REST APIs',
        'ETL',
        'Power BI',
        'OEE',
        'Manufacturing analytics',
        'Modbus',
        'EUROMAP63',
      ],
      languages: ['Spanish - Native', 'English - Professional working proficiency'],
    },
    closing: {
      eyebrow: 'Available for collaboration',
      title:
        'If a company needs cleaner operations through better systems, this is where I fit best.',
      description:
        'I can support MES, Industrial IoT, dashboards, Power BI, reporting automation and connected manufacturing applications.',
      primary: 'Email me',
      quaternary: 'LinkedIn',
    },
    footer: {
      role: 'Data Engineer | Industrial IoT | Manufacturing Systems',
      builtWith: 'Designed in React + Vite + Framer Motion',
    },
  },
  es: {
    brandRole: 'Data Engineer | Industrial IoT | MES',
    imageZoomLabel: 'Abrir imagen',
    imageCloseLabel: 'Cerrar vista de imagen',
    navigation: [
      { label: 'Principal', href: '#featured' },
      { label: 'Sistemas', href: '#systems' },
      { label: 'Experiencia', href: '#experience' },
      { label: 'Educaci\u00f3n', href: '#education' },
      { label: 'Contacto', href: '#contact' },
    ],
    languageSwitchLabel: 'Seleccionar idioma',
    cvLabel: 'Descargar CV',
    githubLabel: 'GitHub',
    hero: {
      badge: 'Portafolio digital para MES, Industrial IoT y anal\u00edtica',
      titleLead: 'Dise\u00f1o sistemas de manufactura que',
      titleAccent: 'convierten datos vivos en control operativo.',
      description:
        'Soy Juan Roberto Garc\u00eda G\u00f3mez, Data Engineer enfocado en MES, Industrial IoT y anal\u00edtica operativa para manufactura.',
      primaryAction: 'Ver dashboard MES principal',
      secondaryAction: 'Abrir CV PDF',
      linkedin: 'LinkedIn',
      portraitAlt: 'Foto profesional de Juan Roberto Garc\u00eda G\u00f3mez',
      focusTitle: 'Lo que aporto a una empresa',
      focusItems: [
        'Dashboards MES en tiempo real para shopfloor y liderazgo',
        'M\u00f3dulos de producci\u00f3n, paros, calidad y planeaci\u00f3n para uso diario',
        'Power BI, ETL y sistemas conectados entre MES y ERP',
      ],
    },
    stats: [
      {
        value: '90%',
        label: 'menos captura manual',
        detail: 'la producci\u00f3n llega en tiempo real y el equipo solo agrega contexto de paros y defectos',
      },
      {
        value: '0 papel',
        label: 'control digital de RH',
        detail: 'asistencias y banco de tiempo ahora corren con conexi\u00f3n al reloj checador y sin hojas',
      },
      {
        value: '24/7',
        label: 'visibilidad del plan',
        detail: 'direcci\u00f3n ve plan vs real, causas de paro y producci\u00f3n corriendo sin plan',
      },
      {
        value: '34',
        label: 'm\u00e1quinas de inyecci\u00f3n conectadas',
        detail: 'integraci\u00f3n Euromap63 y Modbus en m\u00e1quinas ENGEL, WOOJIN y SUMITOMO',
      },
    ],
    showcase: {
      eyebrow: 'Contexto profesional',
      title: 'Reconocimiento, formaci\u00f3n y trayectoria industrial',
      description: 'Una referencia visual breve de las experiencias detr\u00e1s de mi trabajo.',
      publicationLabel: 'Ver en LinkedIn',
      items: [
        {
          title: 'Mejor empleado del departamento del a\u00f1o',
          kicker: 'Reconocimiento',
          text: 'Reconocimiento en Chunil Mexico por disciplina, ejecuci\u00f3n e impacto medible.',
          image: portfolioAssets.award,
          alt: 'Reconocimiento al mejor empleado del departamento del a\u00f1o',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'KeepCoding',
          kicker: 'Formaci\u00f3n avanzada',
          text: 'Bootcamp aplicado a proyectos reales de datos, IA y desarrollo full-stack.',
          image: portfolioAssets.keepCoding,
          alt: 'Certificaci\u00f3n de KeepCoding',
          publicationUrl: contactLinks.linkedin,
        },
        {
          title: 'General Motors SLP',
          kicker: 'Experiencia de negocio',
          text: 'Anal\u00edtica operativa, recuperaci\u00f3n de claims y visibilidad ejecutiva en entorno industrial.',
          image: portfolioAssets.gm,
          alt: 'Imagen del equipo de General Motors San Luis Potos\u00ed',
          publicationUrl: contactLinks.linkedin,
        },
      ],
    },
    featured: {
      eyebrow: 'Sistema principal',
      title: 'Dashboard MES en tiempo real',
      description:
        'Una vista operativa que da visibilidad inmediata del estado de m\u00e1quinas, paros y se\u00f1ales de ejecuci\u00f3n.',
      imageAlt: 'Dashboard MES en tiempo real con live stop board',
      points: [
        'Muestra estado de m\u00e1quinas, stop board y excepciones del plan en una sola pantalla',
        'Ayuda a reaccionar m\u00e1s r\u00e1pido cuando cambia la producci\u00f3n durante el turno',
        'Dise\u00f1ado para control visual claro en shopfloor',
      ],
      metrics: [
        { value: '34', label: 'm\u00e1quinas conectadas' },
        { value: 'Live', label: 'control de stop board' },
        { value: 'Shift', label: 'seguimiento operativo' },
        { value: 'React + Node', label: 'entrega full-stack' },
      ],
    },
    systems: {
      eyebrow: 'Trabajo seleccionado',
      title: 'Sistemas construidos para la operaci\u00f3n',
      description:
        'M\u00f3dulos MES, anal\u00edtica y herramientas de negocio usadas en la operaci\u00f3n diaria.',
      previousLabel: 'Anterior',
      nextLabel: 'Siguiente',
      modulesTitle: 'M\u00f3dulos MES',
      modulesDescription: 'Pantallas operativas dise\u00f1adas para el d\u00eda a d\u00eda en planta.',
      modules: [
        {
          title: 'MES Home',
          subtitle: 'Navegaci\u00f3n principal y acceso en tiempo real',
          description: 'Pantalla principal del MES con acceso directo a m\u00f3dulos y contexto operativo.',
          image: portfolioAssets.mesHome,
          alt: 'Home del MES',
        },
        {
          title: 'Dashboard MES en tiempo real',
          subtitle: 'Live stop board y estado de m\u00e1quinas',
          description: 'Pantalla visual para monitorear estados, excepciones y comportamiento del turno en tiempo real.',
          image: portfolioAssets.mesLiveStopBoard,
          alt: 'Dashboard MES en tiempo real',
        },
        {
          title: 'Weekly Plan Adherence',
          subtitle: 'Objetivo de inyecci\u00f3n contra ejecuci\u00f3n real',
          description: 'Vista semanal para comparar el plan contra la producci\u00f3n real con lectura inmediata.',
          image: portfolioAssets.mesProductionPlan,
          alt: 'Dashboard de Weekly Plan Adherence',
        },
        {
          title: 'Injection Data',
          subtitle: 'Detalle de producci\u00f3n y visibilidad del proceso',
          description: 'Pantalla enfocada en variables de proceso, registros de producci\u00f3n y contexto de inyecci\u00f3n.',
          image: portfolioAssets.injectionData,
          alt: 'Dashboard de Injection Data',
        },
        {
          title: 'Reporte de telemetr\u00eda',
          subtitle: 'Variables de proceso y an\u00e1lisis de ciclo',
          description: 'Vista t\u00e9cnica para revisar cycle time, presi\u00f3n, fill time y comportamiento del proceso.',
          image: portfolioAssets.telemetry,
          alt: 'Reporte de telemetr\u00eda de inyecci\u00f3n',
        },
        {
          title: 'Historial de paros de l\u00ednea',
          subtitle: 'Revisi\u00f3n y justificaci\u00f3n de downtime',
          description: 'Flujo para revisar eventos de paro, ver detalle del downtime y soportar la justificaci\u00f3n.',
          image: portfolioAssets.mesLineStopHistory,
          alt: 'Flujo de historial de paros de l\u00ednea',
        },
        {
          title: 'Estado de mantenimiento preventivo',
          subtitle: 'Runtime de tooling y visibilidad de PM',
          description: 'Dashboard de tooling para ver runtime, moldes vencidos y estado de mantenimiento preventivo.',
          image: portfolioAssets.toolingPm,
          alt: 'Dashboard de mantenimiento preventivo de tooling',
        },
        {
          title: 'Mold Tracking',
          subtitle: 'Seguimiento de tooling',
          description: 'Vista para controlar responsables, avance, fechas y estado de problemas de tooling.',
          image: portfolioAssets.moldTracking,
          alt: 'Sistema de Mold Tracking',
        },
        {
          title: '\u00d3rdenes de mantenimiento',
          subtitle: 'Ejecuci\u00f3n correctiva y preventiva',
          description: 'Vista para gestionar solicitudes de tooling, tipo de mantenimiento y detalle del problema.',
          image: portfolioAssets.moldMaintenanceOrders,
          alt: 'Dashboard de \u00f3rdenes de mantenimiento de tooling',
        },
      ],
      analyticsTitle: 'Anal\u00edtica y revisi\u00f3n de negocio',
      analyticsDescription: 'Vistas ejecutivas que complementan la operaci\u00f3n en tiempo real.',
      analytics: [
        {
          title: 'Power BI Operations Review',
          subtitle: 'Visibilidad para liderazgo',
          description: 'Capa anal\u00edtica para revisiones de producci\u00f3n, control de ejecuci\u00f3n y seguimiento gerencial.',
          image: portfolioAssets.powerbiPlan,
          alt: 'Dashboard Power BI de revisi\u00f3n operativa',
        },
        {
          title: 'Power BI Performance Drivers',
          subtitle: 'Lectura de desempe\u00f1o',
          description: 'Vista complementaria enfocada en tendencias, se\u00f1ales de desempe\u00f1o y drivers operativos.',
          image: portfolioAssets.powerbiDrivers,
          alt: 'Dashboard Power BI de drivers de desempe\u00f1o',
        },
      ],
      enterpriseTitle: 'ERP-System',
      enterpriseDescription: 'Flujos reales del ERP para incidencias y planeaci\u00f3n de inyecci\u00f3n.',
      enterprise: [
        {
          title: 'Incidencias ERP',
          subtitle: 'Flujo de Recursos Humanos',
          description: 'Proceso estructurado para crear, revisar y gestionar incidencias dentro del ERP.',
          image: portfolioAssets.erpIncidencias,
          alt: 'Pantalla de incidencias del ERP',
        },
        {
          title: 'Plan de producci\u00f3n de inyecci\u00f3n',
          subtitle: 'Planeaci\u00f3n y seguimiento',
          description: 'Pantalla enfocada en la programaci\u00f3n de inyecci\u00f3n y el seguimiento de ejecuci\u00f3n.',
          image: portfolioAssets.erpProductionPlan,
          alt: 'Dashboard de planeaci\u00f3n de producci\u00f3n del ERP',
        },
      ],
    },
    support: {
      eyebrow: 'C\u00f3mo puedo ayudar',
      title: 'D\u00f3nde genero m\u00e1s valor',
      description:
        'Genero m\u00e1s valor donde operaci\u00f3n, datos industriales y entrega de software deben avanzar juntos.',
      items: [
        {
          title: 'MES e Industrial IoT',
          text: 'Conecto m\u00e1quinas, l\u00f3gica de planta y flujos de usuario en sistemas que operaci\u00f3n puede usar cada turno.',
        },
        {
          title: 'Dashboards operativos',
          text: 'Construyo vistas en tiempo real que son claras, \u00fatiles y alineadas con decisiones de planta.',
        },
        {
          title: 'Data engineering y ETL',
          text: 'Dise\u00f1o bases de datos, pipelines y reglas de negocio para volver confiables los datos de manufactura.',
        },
        {
          title: 'Power BI y automatizaci\u00f3n',
          text: 'Convierto datos crudos en reportes recurrentes, dashboards gerenciales y anal\u00edtica lista para revisi\u00f3n.',
        },
      ],
    },
    experience: {
      eyebrow: 'Experiencia',
      title: 'Resultados construidos en operaci\u00f3n real',
      description: 'Manufactura, data engineering y anal\u00edtica orientada a resultados de negocio.',
      items: [
        {
          company: 'Chunil Mexico',
          role: 'Data Engineer | MES & Manufacturing Analytics',
          period: 'Oct 2024 - Actualidad',
          summary:
            'Construcci\u00f3n de una plataforma MES productiva para manufactura con integraci\u00f3n industrial, backend, anal\u00edtica y aplicaciones React para shopfloor.',
          bullets: [
            'Centralic\u00e9 inyecci\u00f3n, ensamble, EPC, tooling y operaci\u00f3n de planta en una sola plataforma web.',
            'Integr\u00e9 34 m\u00e1quinas a dashboards en tiempo real, an\u00e1lisis hist\u00f3rico y l\u00f3gica de downtime.',
            'Recib\u00ed el reconocimiento de mejor empleado del departamento del a\u00f1o en mi empresa actual.',
          ],
        },
        {
          company: 'Ramirez Valle & Asociados | General Motors SLP',
          role: 'Claims, Loss & Recovery Coordinator',
          period: 'Oct 2023 - 2024',
          summary:
            'Rol orientado a anal\u00edtica operativa, recuperaci\u00f3n financiera, gesti\u00f3n de evidencia y visibilidad ejecutiva.',
          bullets: [
            'Recuper\u00e9 MX$15.2M mediante an\u00e1lisis data-driven de claims log\u00edsticos.',
            'Constru\u00ed dashboards en Power BI que redujeron 40 por ciento el tiempo de an\u00e1lisis.',
            'Estructur\u00e9 flujos de evidencia y seguimiento para m\u00e1s de 100 casos.',
          ],
        },
      ],
    },
    education: {
      eyebrow: 'Educaci\u00f3n',
      title: 'Formaci\u00f3n y stack principal',
      description: 'Base acad\u00e9mica y t\u00e9cnica aplicada a manufactura y anal\u00edtica.',
      educationTitle: 'Formaci\u00f3n',
      stackTitle: 'Stack principal',
      languagesTitle: 'Idiomas',
      items: [
        'Bootcamp Full Stack Web Development, KeepCoding | Nov 2025 - Actualidad',
        'Business Analytics, Tecnol\u00f3gico de Monterrey | Ene 2025 - Abr 2025',
        'Bootcamp Big Data, AI and Machine Learning, KeepCoding | Jun 2023 - Jun 2024',
        'Python for Data Science, IICO | May 2022 - Ago 2022',
        'Licenciatura en Econom\u00eda, UASLP | Ago 2018 - Jul 2023',
        'Ingenier\u00eda Industrial y Log\u00edstica, UNID | Ago 2014 - Jul 2017',
      ],
      stack: [
        'PostgreSQL',
        'SQL',
        'Node.js',
        'React',
        'Vite',
        'REST APIs',
        'ETL',
        'Power BI',
        'OEE',
        'Manufacturing analytics',
        'Modbus',
        'EUROMAP63',
      ],
      languages: ['Espa\u00f1ol - Nativo', 'Ingl\u00e9s - Nivel profesional de trabajo'],
    },
    closing: {
      eyebrow: 'Disponible para colaborar',
      title:
        'Si una empresa necesita operaciones m\u00e1s limpias a trav\u00e9s de mejores sistemas, ah\u00ed es donde mejor encajo.',
      description:
        'Puedo apoyar en MES, Industrial IoT, dashboards, Power BI, automatizaci\u00f3n de reportes y aplicaciones conectadas para manufactura.',
      primary: 'Escribirme',
      quaternary: 'LinkedIn',
    },
    footer: {
      role: 'Data Engineer | Industrial IoT | Manufacturing Systems',
      builtWith: 'Dise\u00f1ado en React + Vite + Framer Motion',
    },
  },
};
